import type { AssessmentItem } from '../contracts.js'

export const GRAMMAR_ITEMS: readonly AssessmentItem[] = [
  // --------------------------------------------------------------------------
  // 1. basic_sentence_structure (8 items: 4 MCQ, 4 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'grm_sen_01',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Tom and his younger brother ______ in the school library right now.',
    choices: [
      { id: 'A', text: 'are' },
      { id: 'B', text: 'is' },
      { id: 'C', text: 'am' },
      { id: 'D', text: 'be' },
    ],
    correctChoice: 'A',
    analysisTags: ['compound_subject', 'be_verb'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_02',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Choose the correct pronoun (I or me) to complete the subject: "My sister and ______ baked chocolate cookies this morning."',
    acceptedAnswers: ['I'],
    analysisTags: ['pronoun_case', 'subject_syntax'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_03',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: '______ three foreign exchange students visiting our class today.',
    choices: [
      { id: 'A', text: 'There are' },
      { id: 'B', text: 'There is' },
      { id: 'C', text: 'They are' },
      { id: 'D', text: 'It has' },
    ],
    correctChoice: 'A',
    analysisTags: ['existential_there', 'plural_noun'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_04',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Complete the sentence with the correct possessive pronoun: "This blue backpack belongs to Cindy; it is ______."',
    acceptedAnswers: ['hers'],
    analysisTags: ['possessive_pronoun', 'syntax'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_05',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'The freshly baked apple pie on the kitchen table smells ______.',
    choices: [
      { id: 'A', text: 'delicious' },
      { id: 'B', text: 'deliciously' },
      { id: 'C', text: 'deliciousness' },
      { id: 'D', text: 'more deliciously' },
    ],
    correctChoice: 'A',
    analysisTags: ['linking_verb', 'adjective_complement'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_06',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Fill in the correct gerund form of "swim": "During the hot summer months, my brother enjoys ______ in the outdoor pool."',
    acceptedAnswers: ['swimming'],
    analysisTags: ['gerund_object', 'verb_pattern'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_07',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 4,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'The coach made every basketball player ______ twenty laps around the gymnasium.',
    choices: [
      { id: 'A', text: 'run' },
      { id: 'B', text: 'to run' },
      { id: 'C', text: 'running' },
      { id: 'D', text: 'ran' },
    ],
    correctChoice: 'A',
    analysisTags: ['causative_verb', 'bare_infinitive'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_sen_08',
    domain: 'grammar',
    skill: 'basic_sentence_structure',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Fill in the base form or -ing form of "knock": "Late last night, we clearly heard someone ______ on the front wooden door."',
    acceptedAnswers: ['knock', 'knocking'],
    analysisTags: ['sensory_verb', 'participle_complement'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // 2. verb_tense_agreement (10 items: 4 MCQ, 6 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'grm_tns_01',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Mr. Wu ______ to his office by bicycle every weekday morning.',
    choices: [
      { id: 'A', text: 'commutes' },
      { id: 'B', text: 'commute' },
      { id: 'C', text: 'is commute' },
      { id: 'D', text: 'commuting' },
    ],
    correctChoice: 'A',
    analysisTags: ['simple_present', 'third_person_singular'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_02',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Type the simple past tense of "walk": "Yesterday afternoon, grandma ______ her puppy in the community park."',
    acceptedAnswers: ['walked'],
    analysisTags: ['simple_past', 'regular_verb'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_03',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Type the simple past tense of "see": "Last Friday evening, my friends and I ______ an exciting basketball match on television."',
    acceptedAnswers: ['saw'],
    analysisTags: ['simple_past', 'irregular_verb'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_04',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Listen! The school band ______ their final rehearsal in the auditorium.',
    choices: [
      { id: 'A', text: 'is practicing' },
      { id: 'B', text: 'practiced' },
      { id: 'C', text: 'practices' },
      { id: 'D', text: 'will practice' },
    ],
    correctChoice: 'A',
    analysisTags: ['present_continuous', 'cue_word_listen'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_05',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Complete with the future form using "will" and "visit": "Our family ______ Japan during the upcoming winter vacation."',
    acceptedAnswers: ['will visit'],
    analysisTags: ['simple_future', 'modal_auxiliary'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_06',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'While Susan was washing dishes, the telephone in the hallway suddenly ______.',
    choices: [
      { id: 'A', text: 'rang' },
      { id: 'B', text: 'was ringing' },
      { id: 'C', text: 'rings' },
      { id: 'D', text: 'has rung' },
    ],
    correctChoice: 'A',
    analysisTags: ['past_continuous_with_interruption', 'simple_past'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_07',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Type the simple past tense of "fly": "Hundreds of migratory birds ______ south before the severe winter storm arrived."',
    acceptedAnswers: ['flew'],
    analysisTags: ['irregular_verb', 'simple_past'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_08',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Type the past participle of "live" to complete the present perfect tense: "Our neighbors have ______ in this quiet town for more than twenty years."',
    acceptedAnswers: ['lived'],
    analysisTags: ['present_perfect', 'past_participle'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_09',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Have you ever ______ to Sun Moon Lake to watch the sunrise over the misty mountains?',
    choices: [
      { id: 'A', text: 'been' },
      { id: 'B', text: 'gone' },
      { id: 'C', text: 'went' },
      { id: 'D', text: 'go' },
    ],
    correctChoice: 'A',
    analysisTags: ['present_perfect', 'been_to_vs_gone_to'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_tns_10',
    domain: 'grammar',
    skill: 'verb_tense_agreement',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Type the past participle of "destroy" to complete the past perfect tense: "By the time the rescue team arrived, the landslide had already ______ the wooden bridge."',
    acceptedAnswers: ['destroyed'],
    analysisTags: ['past_perfect', 'sequence_of_events'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // 3. questions_and_negatives (8 items: 4 MCQ, 4 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'grm_qneg_01',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Henry ______ drink milk tea because he is sensitive to caffeine.',
    choices: [
      { id: 'A', text: 'does not' },
      { id: 'B', text: 'do not' },
      { id: 'C', text: 'is not' },
      { id: 'D', text: 'are not' },
    ],
    correctChoice: 'A',
    analysisTags: ['negation', 'does_not_third_person'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_02',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Choose Do or Does to complete the question: "______ your parents enjoy hiking in the mountains on weekends?"',
    acceptedAnswers: ['Do'],
    analysisTags: ['yes_no_question', 'auxiliary_do_plural'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_03',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: '"______ is the local night market from our hotel?" — "It is about three kilometers away."',
    choices: [
      { id: 'A', text: 'How far' },
      { id: 'B', text: 'How long' },
      { id: 'C', text: 'How often' },
      { id: 'D', text: 'How much' },
    ],
    correctChoice: 'A',
    analysisTags: ['wh_question', 'distance_expression'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_04',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Fill in the question word asking for location: "______ did you buy those handmade pottery cups?" — "At the Yingge Old Street."',
    acceptedAnswers: ['Where'],
    analysisTags: ['wh_question', 'place_inquiry'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_05',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'You are coming to the science fair with us tomorrow, ______?',
    choices: [
      { id: 'A', text: 'aren’t you' },
      { id: 'B', text: 'don’t you' },
      { id: 'C', text: 'won’t you' },
      { id: 'D', text: 'isn’t it' },
    ],
    correctChoice: 'A',
    analysisTags: ['tag_question', 'be_verb_affirmative_lead'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_06',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Complete the tag question: "David doesn’t eat seafood, ______ he?"',
    acceptedAnswers: ['does'],
    analysisTags: ['tag_question', 'negative_lead_positive_tag'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_07',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Let’s take a short break and grab some iced bubble tea, ______?',
    choices: [
      { id: 'A', text: 'shall we' },
      { id: 'B', text: 'will we' },
      { id: 'C', text: 'don’t we' },
      { id: 'D', text: 'aren’t we' },
    ],
    correctChoice: 'A',
    analysisTags: ['tag_question', 'lets_suggestion'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_qneg_08',
    domain: 'grammar',
    skill: 'questions_and_negatives',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Complete the tag question with the correct auxiliary: "Mr. Lin seldom watches television late at night, ______ he?"',
    acceptedAnswers: ['does'],
    analysisTags: ['tag_question', 'quasi_negative_adverb'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // 4. modifiers_and_relations (8 items: 4 MCQ, 4 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'grm_mod_01',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Our class will take a comprehensive math quiz ______ Friday morning.',
    choices: [
      { id: 'A', text: 'on' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'by' },
    ],
    correctChoice: 'A',
    analysisTags: ['preposition_of_time', 'specific_day_morning'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_02',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Type the preposition meaning below the shade of: "Several tired hikers sat ______ the big banyan tree to rest."',
    acceptedAnswers: ['under', 'beneath'],
    analysisTags: ['preposition_of_place', 'spatial_relation'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_03',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'The typhoon brought torrential rain and fierce winds, ______ all outdoor sports competitions were postponed.',
    choices: [
      { id: 'A', text: 'so' },
      { id: 'B', text: 'because' },
      { id: 'C', text: 'although' },
      { id: 'D', text: 'or' },
    ],
    correctChoice: 'A',
    analysisTags: ['conjunction', 'cause_and_effect'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_04',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Type the comparative form of "fast": "A bullet train travels much ______ than a regular passenger bus."',
    acceptedAnswers: ['faster'],
    analysisTags: ['comparative_degree', 'adverb_comparison'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_05',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Yushan, with an elevation of nearly 4,000 meters, is ______ mountain in Taiwan.',
    choices: [
      { id: 'A', text: 'the highest' },
      { id: 'B', text: 'the most high' },
      { id: 'C', text: 'highest' },
      { id: 'D', text: 'more higher' },
    ],
    correctChoice: 'A',
    analysisTags: ['superlative_degree', 'geography'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_06',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 4,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Fill in the subordinate conjunction meaning in spite of the fact that: "______ it was raining heavily, the dedicated volunteers continued cleaning the beach."',
    acceptedAnswers: ['Although', 'Though'],
    analysisTags: ['concessive_conjunction', 'adverbial_clause'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_07',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'The soup was ______ hot for the little boy to swallow without blowing on it first.',
    choices: [
      { id: 'A', text: 'too' },
      { id: 'B', text: 'so' },
      { id: 'C', text: 'very' },
      { id: 'D', text: 'quite' },
    ],
    correctChoice: 'A',
    analysisTags: ['correlative_modifier', 'too_to_structure'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_mod_08',
    domain: 'grammar',
    skill: 'modifiers_and_relations',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Complete the correlative pair with one word: "Grace is not only an accomplished pianist ______ also an Olympic-level swimmer."',
    acceptedAnswers: ['but'],
    analysisTags: ['correlative_conjunction', 'parallelism'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // 5. complex_structures (10 items: 5 MCQ, 5 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'grm_cpx_01',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Always remember to wash your hands thoroughly before you ______ dinner with your family.',
    choices: [
      { id: 'A', text: 'eat' },
      { id: 'B', text: 'ate' },
      { id: 'C', text: 'will eat' },
      { id: 'D', text: 'eating' },
    ],
    correctChoice: 'A',
    analysisTags: ['time_clause', 'present_replaces_future'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_02',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Fill in the correct present form of "rain" in this conditional sentence: "If it ______ tomorrow, our outdoor sports meet will be moved inside."',
    acceptedAnswers: ['rains'],
    analysisTags: ['first_conditional', 'if_clause'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_03',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'English ______ as an official language in international aviation and maritime communications.',
    choices: [
      { id: 'A', text: 'is used' },
      { id: 'B', text: 'uses' },
      { id: 'C', text: 'was using' },
      { id: 'D', text: 'has used' },
    ],
    correctChoice: 'A',
    analysisTags: ['passive_voice', 'present_passive'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_04',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Type the past participle of "write": "The famous detective novel was ______ by Arthur Conan Doyle."',
    acceptedAnswers: ['written'],
    analysisTags: ['passive_voice', 'past_passive'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_05',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'The dedicated veterinarian ______ treated the injured Formosan deer received a community award.',
    choices: [
      { id: 'A', text: 'who' },
      { id: 'B', text: 'which' },
      { id: 'C', text: 'whom' },
      { id: 'D', text: 'whose' },
    ],
    correctChoice: 'A',
    analysisTags: ['relative_clause', 'relative_pronoun_person'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_06',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Type the relative pronoun (which or that) referring to a vehicle: "The solar bus ______ runs between the harbor and downtown operates every ten minutes."',
    acceptedAnswers: ['that', 'which'],
    analysisTags: ['relative_clause', 'inanimate_relative_pronoun'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_07',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Climatologists warn ______ global temperatures will continue rising if carbon emissions are not reduced.',
    choices: [
      { id: 'A', text: 'that' },
      { id: 'B', text: 'what' },
      { id: 'C', text: 'which' },
      { id: 'D', text: 'who' },
    ],
    correctChoice: 'A',
    analysisTags: ['noun_clause', 'that_conjunction'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_08',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Complete the indirect question with the correct form of "be": "Excuse me, could you tell me where the nearest train station ______?"',
    acceptedAnswers: ['is'],
    analysisTags: ['indirect_question', 'word_order'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_09',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'I recently met a young software engineer ______ mobile app won the national innovation contest.',
    choices: [
      { id: 'A', text: 'whose' },
      { id: 'B', text: 'who' },
      { id: 'C', text: 'which' },
      { id: 'D', text: 'whom' },
    ],
    correctChoice: 'A',
    analysisTags: ['relative_clause', 'possessive_relative_pronoun'],
    status: 'active',
    version: 1,
  },
  {
    id: 'grm_cpx_10',
    domain: 'grammar',
    skill: 'complex_structures',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Complete the passive with the past participle of "recycle": "In Taiwan, all plastic bottles and aluminum cans must be ______."',
    acceptedAnswers: ['recycled'],
    analysisTags: ['modal_passive', 'passive_voice'],
    status: 'active',
    version: 1,
  },
] as const
