import type { AssessmentItem } from '../contracts.js'

export const READING_ITEMS: readonly AssessmentItem[] = [
  // --------------------------------------------------------------------------
  // pass_01: The Sunny Neighborhood Garden (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_01',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_01',
    prompt: 'According to the passage, where are excess vegetables placed for people in need?',
    choices: [
      { id: 'A', text: 'in a wooden basket near the gate' },
      { id: 'B', text: 'inside the community parking lot' },
      { id: 'C', text: 'at the local supermarket counter' },
      { id: 'D', text: 'in front of Mr. Lin’s house' },
    ],
    correctChoice: 'A',
    analysisTags: ['detail_retrieval', 'location'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_mid_01',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_01',
    prompt: 'What is the main topic of the passage?',
    choices: [
      { id: 'A', text: 'How a community garden brought neighbors together' },
      { id: 'B', text: 'The financial cost of buying fresh vegetables' },
      { id: 'C', text: 'Why parking lots should be closed in cities' },
      { id: 'D', text: 'How to plant organic tomatoes in hot weather' },
    ],
    correctChoice: 'A',
    analysisTags: ['main_topic', 'community'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_01',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_01',
    prompt: 'How did the empty lot change after becoming a community garden?',
    choices: [
      { id: 'A', text: 'It changed from an unused space into a lively social hub.' },
      { id: 'B', text: 'It became a crowded commercial parking business.' },
      { id: 'C', text: 'It was sold to a private construction company.' },
      { id: 'D', text: 'It created disagreements between children and grandparents.' },
    ],
    correctChoice: 'A',
    analysisTags: ['synthesis', 'before_and_after'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_02: Notice: Lost Calico Kitten (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_02',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    passageId: 'pass_02',
    prompt: 'According to the notice, what color is the collar that Mochi wears?',
    acceptedAnswers: ['pink', 'a pink collar'],
    analysisTags: ['detail_retrieval', 'factual_attribute'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_01',
    domain: 'reading',
    skill: 'inference',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_02',
    prompt: 'Why does the notice ask people NOT to run toward Mochi if they see her?',
    choices: [
      { id: 'A', text: 'She gets scared easily and might run away.' },
      { id: 'B', text: 'She is dangerous and bites strangers.' },
      { id: 'C', text: 'She has already been found by the police.' },
      { id: 'D', text: 'Her collar has a tracker that stops working if chased.' },
    ],
    correctChoice: 'A',
    analysisTags: ['inference', 'behavioral_cause'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_03: Grandpa Chen’s Early Morning Bakery (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_03',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_03',
    prompt: 'Why does Grandpa Chen avoid using modern electric dough mixers?',
    choices: [
      { id: 'A', text: 'He believes hand-kneading makes the bread soft and bouncy.' },
      { id: 'B', text: 'Electric mixers are too expensive to repair.' },
      { id: 'C', text: 'His small brick oven cannot fit mixer parts.' },
      { id: 'D', text: 'The bakery lacks electrical wiring before dawn.' },
    ],
    correctChoice: 'A',
    analysisTags: ['factual_detail', 'motivation'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_vic_01',
    domain: 'reading',
    skill: 'vocabulary_in_context',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_03',
    prompt: 'In the passage, what does the word "stretch" mean in the phrase "stretch down the sidewalk"?',
    choices: [
      { id: 'A', text: 'extend in a continuous long line' },
      { id: 'B', text: 'do physical warm-up exercises' },
      { id: 'C', text: 'pull something until it breaks' },
      { id: 'D', text: 'widen the paved walkway' },
    ],
    correctChoice: 'A',
    analysisTags: ['contextual_clue', 'phrase_meaning'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_02',
    domain: 'reading',
    skill: 'inference',
    difficulty: 3,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_03',
    prompt: 'What can we infer about Grandpa Chen from the passage?',
    choices: [
      { id: 'A', text: 'He takes immense pride in his traditional craft.' },
      { id: 'B', text: 'He plans to retire and close the bakery soon.' },
      { id: 'C', text: 'He prefers selling western cakes over traditional buns.' },
      { id: 'D', text: 'He only bakes when students ask him to.' },
    ],
    correctChoice: 'A',
    analysisTags: ['character_inference', 'deduction'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_04: The Plastic Bottle Rocket Experiment (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_04',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_04',
    prompt: 'What was the purpose of attaching cardboard triangles to the bottle neck?',
    choices: [
      { id: 'A', text: 'To act as steering fins' },
      { id: 'B', text: 'To stop water from leaking out' },
      { id: 'C', text: 'To make the rocket heavier' },
      { id: 'D', text: 'To connect the bicycle pump' },
    ],
    correctChoice: 'A',
    analysisTags: ['detail_retrieval', 'purpose'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_mid_02',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    passageId: 'pass_04',
    prompt: 'Which title best summarizes this passage?',
    choices: [
      { id: 'A', text: 'Building and Launching a Water Rocket' },
      { id: 'B', text: 'The Dangers of High Air Pressure' },
      { id: 'C', text: 'How to Recycle Plastic Soda Bottles' },
      { id: 'D', text: 'Tina’s Favorite Friday Science Class' },
    ],
    correctChoice: 'A',
    analysisTags: ['title_selection', 'gist'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_05: Cycling Along the Pacific Highway (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_mid_03',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_05',
    prompt: 'What is the main lesson Leo learned from his bicycle tour?',
    choices: [
      { id: 'A', text: 'Perseverance and endurance matter more than finishing fast.' },
      { id: 'B', text: 'East Coast headwinds make cycling impossible in summer.' },
      { id: 'C', text: 'It is safer to travel by train than by bicycle.' },
      { id: 'D', text: 'Convenience stores sell the best cycling equipment.' },
    ],
    correctChoice: 'A',
    analysisTags: ['theme', 'moral_takeaway'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_03',
    domain: 'reading',
    skill: 'inference',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_05',
    prompt: 'Why did the shouts of "Jiayou!" help Leo during the hardest parts of the ride?',
    choices: [
      { id: 'A', text: 'They provided emotional encouragement when he was exhausted.' },
      { id: 'B', text: 'They warned him about dangerous road construction ahead.' },
      { id: 'C', text: 'They instructed him which gear to use on steep hills.' },
      { id: 'D', text: 'They reminded him to catch up with his father.' },
    ],
    correctChoice: 'A',
    analysisTags: ['inference', 'psychological_effect'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_02',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    passageId: 'pass_05',
    prompt: 'According to the passage, how many days did the bicycle tour take?',
    acceptedAnswers: ['five', '5', 'five days', '5 days'],
    analysisTags: ['factual_integration', 'numerical_retrieval'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_06: The Silent Glow of Mountain Fireflies (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_05',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_06',
    prompt: 'What are nighttime visitors required to wrap around their flashlights?',
    choices: [
      { id: 'A', text: 'red cellophane paper' },
      { id: 'B', text: 'dark green cloth' },
      { id: 'C', text: 'thick black electrical tape' },
      { id: 'D', text: 'yellow waterproof plastic' },
    ],
    correctChoice: 'A',
    analysisTags: ['factual_detail', 'regulation'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_vic_02',
    domain: 'reading',
    skill: 'vocabulary_in_context',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_06',
    prompt: 'In the passage, what does the word "disrupt" mean in the context of firefly courtship?',
    choices: [
      { id: 'A', text: 'interrupt or throw into confusion' },
      { id: 'B', text: 'speed up and improve' },
      { id: 'C', text: 'illuminate more brightly' },
      { id: 'D', text: 'protect from natural enemies' },
    ],
    correctChoice: 'A',
    analysisTags: ['contextual_vocabulary', 'ecological_context'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_04',
    domain: 'reading',
    skill: 'inference',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_06',
    prompt: 'Why would bright white light interfere with firefly mating?',
    choices: [
      { id: 'A', text: 'It overpowers their subtle bioluminescent flashes, making signals unreadable.' },
      { id: 'B', text: 'It heats up the forest trail and harms tree roots.' },
      { id: 'C', text: 'It causes fireflies to lose their wings.' },
      { id: 'D', text: 'It attracts bats that hunt only in bright light.' },
    ],
    correctChoice: 'A',
    analysisTags: ['scientific_inference', 'cause_and_effect'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_07: National Railway Museum Weekend Volunteer Schedule (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_06',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    passageId: 'pass_07',
    prompt: 'According to the notice, in which room does the mandatory volunteer briefing take place?',
    acceptedAnswers: ['Conference Room 201', 'Room 201', '201'],
    analysisTags: ['notice_detail', 'room_number'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_03',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_07',
    prompt: 'If a student volunteer works Shift A, which of the following is true?',
    choices: [
      { id: 'A', text: 'They work from 9:00 AM to 1:00 PM and receive four service hours.' },
      { id: 'B', text: 'They guide visitors in the locomotive warehouse until 5:30 PM.' },
      { id: 'C', text: 'They do not need to attend the morning briefing.' },
      { id: 'D', text: 'They must bring their own lunch from home.' },
    ],
    correctChoice: 'A',
    analysisTags: ['schedule_synthesis', 'comparison'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_08: A Postcard from Green Island (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_07',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_08',
    prompt: 'Where did Kevin go snorkeling with his instructor?',
    choices: [
      { id: 'A', text: 'At the coral reef at Chaikou' },
      { id: 'B', text: 'Inside the Zhaori Hot Springs' },
      { id: 'C', text: 'Beside the harbor ferry dock' },
      { id: 'D', text: 'Near the island airport runway' },
    ],
    correctChoice: 'A',
    analysisTags: ['factual_detail', 'location'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_05',
    domain: 'reading',
    skill: 'inference',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_08',
    prompt: 'What was the author’s tone in this postcard?',
    choices: [
      { id: 'A', text: 'Enthusiastic and delighted' },
      { id: 'B', text: 'Homesick and worried' },
      { id: 'C', text: 'Bored and disappointed' },
      { id: 'D', text: 'Apologetic and regretful' },
    ],
    correctChoice: 'A',
    analysisTags: ['tone_inference', 'author_attitude'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_04',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 4,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_08',
    prompt: 'Based on the postcard, what does Kevin’s travel itinerary look like?',
    choices: [
      { id: 'A', text: 'Ferry arrival yesterday, snorkeling this morning, and hot springs tonight.' },
      { id: 'B', text: 'Snorkeling yesterday, ferry departure this morning, and flight tonight.' },
      { id: 'C', text: 'Hot springs yesterday, ferry ride this morning, and snorkeling tomorrow.' },
      { id: 'D', text: 'Resting yesterday, airport arrival this morning, and swimming tomorrow.' },
    ],
    correctChoice: 'A',
    analysisTags: ['chronology_integration', 'itinerary'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_09: The Unexpected Summer Downpour (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_mid_04',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_09',
    prompt: 'What does this passage primarily depict?',
    choices: [
      { id: 'A', text: 'A sudden, brief summer thunderstorm and its immediate aftermath' },
      { id: 'B', text: 'The severe financial losses of outdoor fruit vendors' },
      { id: 'C', text: 'Why city sewer drainage systems fail during typhoon season' },
      { id: 'D', text: 'The scientific atmospheric cause of rainbow formation' },
    ],
    correctChoice: 'A',
    analysisTags: ['passage_gist', 'descriptive_narrative'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_vic_03',
    domain: 'reading',
    skill: 'vocabulary_in_context',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_09',
    prompt: 'In the passage, what does the word "abruptly" mean in the phrase "as abruptly as it had arrived"?',
    choices: [
      { id: 'A', text: 'suddenly and unexpectedly' },
      { id: 'B', text: 'quietly and slowly' },
      { id: 'C', text: 'according to a schedule' },
      { id: 'D', text: 'with great difficulty' },
    ],
    correctChoice: 'A',
    analysisTags: ['adverb_meaning', 'contextual_clue'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_10: Student Forum: Digital Tablets vs. Paper Notebooks (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_mid_05',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_10',
    prompt: 'What is the main debate discussed in this forum passage?',
    choices: [
      { id: 'A', text: 'The advantages and drawbacks of digital tablets versus paper notebooks in school' },
      { id: 'B', text: 'The cost of purchasing interactive science software licenses' },
      { id: 'C', text: 'Why social media should be banned from all school campuses' },
      { id: 'D', text: 'How to reduce the weight of student backpacks with e-readers' },
    ],
    correctChoice: 'A',
    analysisTags: ['central_argument', 'forum_topic'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_05',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 4,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_10',
    prompt: 'How does Teacher Wang’s proposal resolve the disagreement between Emily and Marcus?',
    choices: [
      { id: 'A', text: 'By combining tablets for interactive simulations with handwriting for math and reflection' },
      { id: 'B', text: 'By banning tablets completely in all classrooms to prevent distraction' },
      { id: 'C', text: 'By requiring all textbooks to be printed on recycled paper' },
      { id: 'D', text: 'By letting students vote on whether to bring smartphones to school' },
    ],
    correctChoice: 'A',
    analysisTags: ['point_of_view_synthesis', 'compromise'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_06',
    domain: 'reading',
    skill: 'inference',
    difficulty: 4,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    passageId: 'pass_10',
    prompt: 'What concern does Marcus have about using tablets that Emily does not mention?',
    choices: [
      { id: 'A', text: 'The threat of online notifications diverting student focus away from lessons' },
      { id: 'B', text: 'The high electricity consumption of charging devices overnight' },
      { id: 'C', text: 'The physical fragility of tablet glass screens when dropped' },
      { id: 'D', text: 'The difficulty of typing Chinese characters on digital keyboards' },
    ],
    correctChoice: 'A',
    analysisTags: ['contrastive_inference', 'implicit_objection'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_11: Protecting the Formosan Black Bear (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_exp_08',
    domain: 'reading',
    skill: 'explicit_information',
    difficulty: 3,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_11',
    prompt: 'What distinctive physical characteristic identifies the Formosan black bear?',
    choices: [
      { id: 'A', text: 'A white crescent V-shape on its chest' },
      { id: 'B', text: 'Golden spots across its back' },
      { id: 'C', text: 'A short white tail and gray paws' },
      { id: 'D', text: 'Long curved tusks beside its snout' },
    ],
    correctChoice: 'A',
    analysisTags: ['zoological_detail', 'identification'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_vic_04',
    domain: 'reading',
    skill: 'vocabulary_in_context',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_11',
    prompt: 'In the passage, what does the word "solitary" mean in "these solitary omnivores"?',
    choices: [
      { id: 'A', text: 'living and hunting alone rather than in groups' },
      { id: 'B', text: 'fierce and aggressive toward humans' },
      { id: 'C', text: 'sleeping throughout the entire winter season' },
      { id: 'D', text: 'traveling long distances along public roads' },
    ],
    correctChoice: 'A',
    analysisTags: ['contextual_clue', 'biological_term'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_07',
    domain: 'reading',
    skill: 'inference',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_11',
    prompt: 'Why do conservation biologists recommend establishing wildlife corridors across mountain roads?',
    choices: [
      { id: 'A', text: 'To reconnect fragmented habitats so bears can safely find food and mates' },
      { id: 'B', text: 'To allow tourists to photograph bears without leaving their vehicles' },
      { id: 'C', text: 'To trap bears and transport them into national zoos' },
      { id: 'D', text: 'To keep wild bears away from mountain acorn trees' },
    ],
    correctChoice: 'A',
    analysisTags: ['conservation_inference', 'problem_solution'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_12: The Art of Taiwanese Hand Puppetry (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_mid_06',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_12',
    prompt: 'What is the central focus of the passage on Budaixi?',
    choices: [
      { id: 'A', text: 'The rich traditions of hand puppetry and how modern troupes revitalize it' },
      { id: 'B', text: 'Why video games are replacing live performing arts in Taiwan' },
      { id: 'C', text: 'The technical process of carving wooden puppet heads' },
      { id: 'D', text: 'The biographies of famous classical Chinese opera singers' },
    ],
    correctChoice: 'A',
    analysisTags: ['cultural_theme', 'heritage'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_vic_05',
    domain: 'reading',
    skill: 'vocabulary_in_context',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_12',
    prompt: 'In the passage, what does the phrase "breathing vivid life into" mean?',
    choices: [
      { id: 'A', text: 'making inanimate objects seem energetic and real' },
      { id: 'B', text: 'blowing air into hollow wooden toys' },
      { id: 'C', text: 'providing medical mouth-to-mouth resuscitation' },
      { id: 'D', text: 'painting colorful patterns onto silk costumes' },
    ],
    correctChoice: 'A',
    analysisTags: ['figurative_language', 'idiomatic_expression'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_13: Campus Waste Reduction Audit Report (3 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_mid_07',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_13',
    prompt: 'What is the main purpose of this audit report?',
    choices: [
      { id: 'A', text: 'To demonstrate how student initiatives and discounts successfully cut campus waste' },
      { id: 'B', text: 'To complain about poor sanitary conditions in the school cafeteria' },
      { id: 'C', text: 'To encourage students to stop purchasing bubble tea near school' },
      { id: 'D', text: 'To calculate the monetary profit of local beverage businesses' },
    ],
    correctChoice: 'A',
    analysisTags: ['report_objective', 'environmental_audit'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_06',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_13',
    prompt: 'Which strategy directly led to the 48% reduction in single-use beverage waste?',
    choices: [
      { id: 'A', text: 'Offering a monetary discount for customers bringing reusable tumblers' },
      { id: 'B', text: 'Banning all plastic drink containers from being brought on campus' },
      { id: 'C', text: 'Fining students who threw away disposable lunchboxes' },
      { id: 'D', text: 'Replacing tea stands with outdoor water fountains' },
    ],
    correctChoice: 'A',
    analysisTags: ['cause_and_effect_integration', 'policy_result'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_08',
    domain: 'reading',
    skill: 'inference',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    passageId: 'pass_13',
    prompt: 'According to the report, by what exact percentage did disposable drink container waste decrease after one month?',
    acceptedAnswers: ['48%', '48 percent', '48'],
    analysisTags: ['data_retrieval', 'percentage'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_14: The Global Journey of Bubble Tea (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_vic_06',
    domain: 'reading',
    skill: 'vocabulary_in_context',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_14',
    prompt: 'In the passage, what does the word "phenomenon" describe?',
    choices: [
      { id: 'A', text: 'a remarkable, widely popular trend or occurrence' },
      { id: 'B', text: 'a dangerous weather event' },
      { id: 'C', text: 'a temporary scientific error' },
      { id: 'D', text: 'an ancient ceremonial ritual' },
    ],
    correctChoice: 'A',
    analysisTags: ['advanced_vocabulary', 'cultural_phenomenon'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_07',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_14',
    prompt: 'According to food historians, which two factors explain bubble tea’s global appeal?',
    choices: [
      { id: 'A', text: 'The bouncy tapioca texture and adjustable sweetness options' },
      { id: 'B', text: 'The low production cost and hot serving temperature' },
      { id: 'C', text: 'The presence of organic milk and traditional Chinese herbal medicine' },
      { id: 'D', text: 'Exclusive availability in large metropolitan subway stations' },
    ],
    correctChoice: 'A',
    analysisTags: ['multi_factor_synthesis', 'culinary_analysis'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_15: The Tainan Floating Solar Farm (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_int_08',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_15',
    prompt: 'How does locating solar panels on water provide mutual benefits for both energy generation and pond ecology?',
    choices: [
      { id: 'A', text: 'Water cools the panels to boost power output, while panels shade water to reduce evaporation and algae.' },
      { id: 'B', text: 'Panels heat the pond to accelerate fish breeding, while fish clean the panel glass.' },
      { id: 'C', text: 'Panels filter muddy water for irrigation, while pond waves generate tidal electricity.' },
      { id: 'D', text: 'The system eliminates all commercial fish farming in coastal Tainan.' },
    ],
    correctChoice: 'A',
    analysisTags: ['symbiotic_synthesis', 'renewable_technology'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_inf_09',
    domain: 'reading',
    skill: 'inference',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_15',
    prompt: 'Why is floating solar particularly advantageous for a densely populated island like Taiwan?',
    choices: [
      { id: 'A', text: 'It generates clean electricity without competing for scarce agricultural or urban land.' },
      { id: 'B', text: 'It prevents typhoons from making landfall along the southwestern coast.' },
      { id: 'C', text: 'It produces electricity even at midnight when there is no sunshine.' },
      { id: 'D', text: 'It eliminates the need for high-voltage transmission cables.' },
    ],
    correctChoice: 'A',
    analysisTags: ['spatial_inference', 'societal_benefit'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // pass_16: The Sun Moon Lake Swimming Carnival (2 items)
  // --------------------------------------------------------------------------
  {
    id: 'read_mid_08',
    domain: 'reading',
    skill: 'main_idea',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    passageId: 'pass_16',
    prompt: 'What is the primary spirit of the Sun Moon Lake Swimming Carnival as portrayed in the passage?',
    choices: [
      { id: 'A', text: 'Participating for fitness, friendship, and natural beauty rather than winning medals' },
      { id: 'B', text: 'Competing for record-breaking speed and championship cash prizes' },
      { id: 'C', text: 'Promoting competitive triathlon gear manufactured in Taiwan' },
      { id: 'D', text: 'Testing emergency rescue response times on alpine lakes' },
    ],
    correctChoice: 'A',
    analysisTags: ['central_philosophy', 'sports_culture'],
    status: 'active',
    version: 1,
  },
  {
    id: 'read_int_09',
    domain: 'reading',
    skill: 'information_integration',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    passageId: 'pass_16',
    prompt: 'According to the passage, how long is the open-water swimming course in kilometers?',
    acceptedAnswers: ['three', '3', '3 kilometers', '3 km', 'three kilometers'],
    analysisTags: ['factual_retrieval', 'course_length'],
    status: 'active',
    version: 1,
  },
] as const
