import type { AssessmentItem } from '../contracts.js'

export const VOCABULARY_ITEMS: readonly AssessmentItem[] = [
  // --------------------------------------------------------------------------
  // 1. core_vocabulary (8 items: 6 MCQ, 2 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'voc_core_01',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Which place is specifically designed for students to borrow books and study quietly?',
    choices: [
      { id: 'A', text: 'a library' },
      { id: 'B', text: 'a bakery' },
      { id: 'C', text: 'a stadium' },
      { id: 'D', text: 'a clinic' },
    ],
    correctChoice: 'A',
    analysisTags: ['place_noun', 'definition'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_02',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Type the English word for a person whose job is to put out fires and rescue people.',
    acceptedAnswers: ['firefighter', 'fireman'],
    analysisTags: ['occupation_noun', 'spelling'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_03',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'The young puppy was very ______; it sniffed every corner of the new living room.',
    choices: [
      { id: 'A', text: 'curious' },
      { id: 'B', text: 'crowded' },
      { id: 'C', text: 'painful' },
      { id: 'D', text: 'bitter' },
    ],
    correctChoice: 'A',
    analysisTags: ['adjective', 'personality_trait'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_04',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Living near the subway station is very ______ because you can reach school in ten minutes.',
    choices: [
      { id: 'A', text: 'convenient' },
      { id: 'B', text: 'dangerous' },
      { id: 'C', text: 'shy' },
      { id: 'D', text: 'impatient' },
    ],
    correctChoice: 'A',
    analysisTags: ['adjective', 'daily_life'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_05',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Dumping toxic waste into rivers will seriously ______ clean drinking water for local communities.',
    choices: [
      { id: 'A', text: 'pollute' },
      { id: 'B', text: 'celebrate' },
      { id: 'C', text: 'encourage' },
      { id: 'D', text: 'pronounce' },
    ],
    correctChoice: 'A',
    analysisTags: ['verb', 'environment'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_06',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Type the single English noun for an optical instrument used to observe distant stars and planets in the night sky.',
    acceptedAnswers: ['telescope'],
    analysisTags: ['science_noun', 'spelling'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_07',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Because their natural bamboo forests are disappearing, giant pandas are classified as a(n) ______ species.',
    choices: [
      { id: 'A', text: 'endangered' },
      { id: 'B', text: 'artificial' },
      { id: 'C', text: 'fashionable' },
      { id: 'D', text: 'temporary' },
    ],
    correctChoice: 'A',
    analysisTags: ['adjective', 'conservation'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_core_08',
    domain: 'vocabulary',
    skill: 'core_vocabulary',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Solar and wind power are examples of ______ energy because they do not deplete Earth’s natural resources.',
    choices: [
      { id: 'A', text: 'sustainable' },
      { id: 'B', text: 'suspicious' },
      { id: 'C', text: 'superficial' },
      { id: 'D', text: 'accidental' },
    ],
    correctChoice: 'A',
    analysisTags: ['adjective', 'advanced_environment'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // 2. contextual_meaning (8 items: 6 MCQ, 2 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'voc_ctx_01',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Read the sentence: "Walk two blocks, and the post office is on your right." What does "right" mean here?',
    choices: [
      { id: 'A', text: 'the side opposite to left' },
      { id: 'B', text: 'correct and true' },
      { id: 'C', text: 'a moral entitlement' },
      { id: 'D', text: 'immediately or exactly' },
    ],
    correctChoice: 'A',
    analysisTags: ['polysemy', 'direction'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_02',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Read the sentence: "The express train leaves the station at ten o’clock sharp." What does "leaves" mean here?',
    choices: [
      { id: 'A', text: 'departs or goes away from' },
      { id: 'B', text: 'green parts of a plant' },
      { id: 'C', text: 'allows something to remain' },
      { id: 'D', text: 'forgets to bring something' },
    ],
    correctChoice: 'A',
    analysisTags: ['polysemy', 'verb_definition'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_03',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Read the sentence: "The rough bark of the hundred-year-old pine tree protected it from forest insects." What does "bark" mean here?',
    choices: [
      { id: 'A', text: 'the tough outer covering of a tree trunk' },
      { id: 'B', text: 'the sharp loud cry of a guard dog' },
      { id: 'C', text: 'a small wooden sailboat' },
      { id: 'D', text: 'to shout commands angrily' },
    ],
    correctChoice: 'A',
    analysisTags: ['polysemy', 'nature'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_04',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Read the sentence: "The teacher treated every student in a fair manner during the speech contest." What does "fair" mean here?',
    choices: [
      { id: 'A', text: 'treating everyone equally without favoritism' },
      { id: 'B', text: 'light in color or pale' },
      { id: 'C', text: 'an outdoor market or carnival' },
      { id: 'D', text: 'pleasant and dry weather' },
    ],
    correctChoice: 'A',
    analysisTags: ['polysemy', 'justice'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_05',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Complete the sentence with the four-letter word meaning a queue of people waiting: "We waited in a long ______ outside the movie theater for tickets."',
    acceptedAnswers: ['line'],
    analysisTags: ['polysemy', 'fill_in_context'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_06',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Read the sentence: "Strong oceanic currents carried the fishing vessel several miles off course." What does "currents" mean here?',
    choices: [
      { id: 'A', text: 'continuous movements of water in a particular direction' },
      { id: 'B', text: 'belonging to the present time' },
      { id: 'C', text: 'small dried sweet grapes' },
      { id: 'D', text: 'widely accepted rumors' },
    ],
    correctChoice: 'A',
    analysisTags: ['polysemy', 'geography'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_07',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Fill in the word meaning a banking arrangement: "Kevin opened a savings ______ at the post office to deposit his red envelope money."',
    acceptedAnswers: ['account'],
    analysisTags: ['polysemy', 'financial_noun'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_ctx_08',
    domain: 'vocabulary',
    skill: 'contextual_meaning',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Read the sentence: "The young architect proposed a novel solution to cool high-rise buildings using natural sea breezes." What does "novel" mean here?',
    choices: [
      { id: 'A', text: 'original, fresh, and interestingly new' },
      { id: 'B', text: 'a long printed narrative story' },
      { id: 'C', text: 'heavy and complicated to understand' },
      { id: 'D', text: 'costly and difficult to maintain' },
    ],
    correctChoice: 'A',
    analysisTags: ['polysemy', 'advanced_adjective'],
    status: 'active',
    version: 1,
  },

  // --------------------------------------------------------------------------
  // 3. word_form_usage (8 items: 4 MCQ, 4 Short-Answer)
  // --------------------------------------------------------------------------
  {
    id: 'voc_form_01',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 1,
    gradeBand: 'grade_7',
    responseType: 'single_choice',
    prompt: 'Jenny sings ______ in the school choir; her voice always moves the audience.',
    choices: [
      { id: 'A', text: 'sweetly' },
      { id: 'B', text: 'sweet' },
      { id: 'C', text: 'sweetness' },
      { id: 'D', text: 'sweeten' },
    ],
    correctChoice: 'A',
    analysisTags: ['adverb_formation', 'syntax'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_02',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 2,
    gradeBand: 'grade_7',
    responseType: 'short_answer',
    prompt: 'Change the word in parentheses to its correct plural form: "The old house had several ______ (mouse) hiding inside the barn."',
    acceptedAnswers: ['mice'],
    analysisTags: ['irregular_plural', 'morphology'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_03',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 2,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Students are reminded to pay close attention ______ the laboratory safety instructions.',
    choices: [
      { id: 'A', text: 'to' },
      { id: 'B', text: 'at' },
      { id: 'C', text: 'with' },
      { id: 'D', text: 'from' },
    ],
    correctChoice: 'A',
    analysisTags: ['preposition_collocation', 'verb_phrase'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_04',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'short_answer',
    prompt: 'Type the comparative form of "bad" to complete the sentence: "Today’s cold wave is even ______ than yesterday’s chilly weather."',
    acceptedAnswers: ['worse'],
    analysisTags: ['irregular_comparative', 'morphology'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_05',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 3,
    gradeBand: 'grade_8',
    responseType: 'single_choice',
    prompt: 'Drinking sufficient water and getting enough sleep are vital for maintaining good ______. ',
    choices: [
      { id: 'A', text: 'health' },
      { id: 'B', text: 'healthy' },
      { id: 'C', text: 'healthily' },
      { id: 'D', text: 'healthier' },
    ],
    correctChoice: 'A',
    analysisTags: ['noun_formation', 'parts_of_speech'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_06',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Add the correct negative prefix to "possible" to complete the sentence: "It is completely ______ for humans to survive on Mars without pressurized oxygen."',
    acceptedAnswers: ['impossible'],
    analysisTags: ['negative_prefix', 'morphology'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_07',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 4,
    gradeBand: 'grade_9',
    responseType: 'single_choice',
    prompt: 'Parents take great pride ______ their children’s honest efforts and steady improvement.',
    choices: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'for' },
    ],
    correctChoice: 'A',
    analysisTags: ['fixed_collocation', 'preposition'],
    status: 'active',
    version: 1,
  },
  {
    id: 'voc_form_08',
    domain: 'vocabulary',
    skill: 'word_form_usage',
    difficulty: 5,
    gradeBand: 'grade_9',
    responseType: 'short_answer',
    prompt: 'Convert the verb "perform" into its corresponding noun: "The orchestra’s outstanding ______ earned a standing ovation from the crowd."',
    acceptedAnswers: ['performance'],
    analysisTags: ['nominalization', 'suffix_derivation'],
    status: 'active',
    version: 1,
  },
] as const
