import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { REPO_ROOT } from '../src/bundle-compiler.js'

// Official Taiwan Junior High 1,200 Basic Words + 800 Extension Words (2,000 Common Words)
const core1200Words: [string, string][] = [
  ['a', 'art.'], ['about', 'prep.'], ['above', 'prep.'], ['across', 'prep.'], ['act', 'v.'], ['action', 'n.'], ['actor', 'n.'], ['actress', 'n.'],
  ['afraid', 'adj.'], ['after', 'prep.'], ['afternoon', 'n.'], ['again', 'adv.'], ['against', 'prep.'], ['age', 'n.'], ['ago', 'adv.'], ['agree', 'v.'],
  ['ahead', 'adv.'], ['air', 'n.'], ['airplane', 'n.'], ['airport', 'n.'], ['all', 'adj.'], ['almost', 'adv.'], ['alone', 'adj.'], ['along', 'prep.'],
  ['already', 'adv.'], ['also', 'adv.'], ['always', 'adv.'], ['am', 'v.'], ['America', 'n.'], ['American', 'adj.'], ['and', 'conj.'], ['angry', 'adj.'],
  ['animal', 'n.'], ['another', 'adj.'], ['answer', 'n.'], ['ant', 'n.'], ['any', 'adj.'], ['anyone', 'pron.'], ['anything', 'pron.'], ['apartment', 'n.'],
  ['appear', 'v.'], ['apple', 'n.'], ['April', 'n.'], ['are', 'v.'], ['arm', 'n.'], ['around', 'prep.'], ['arrive', 'v.'], ['art', 'n.'],
  ['as', 'prep.'], ['ask', 'v.'], ['at', 'prep.'], ['August', 'n.'], ['aunt', 'n.'], ['autumn', 'n.'], ['away', 'adv.'], ['baby', 'n.'],
  ['back', 'n.'], ['bad', 'adj.'], ['bag', 'n.'], ['bakery', 'n.'], ['ball', 'n.'], ['banana', 'n.'], ['band', 'n.'], ['bank', 'n.'],
  ['baseball', 'n.'], ['basket', 'n.'], ['basketball', 'n.'], ['bat', 'n.'], ['bath', 'n.'], ['bathroom', 'n.'], ['be', 'v.'], ['beach', 'n.'],
  ['bear', 'n.'], ['beautiful', 'adj.'], ['because', 'conj.'], ['become', 'v.'], ['bed', 'n.'], ['bedroom', 'n.'], ['bee', 'n.'], ['beef', 'n.'],
  ['before', 'prep.'], ['begin', 'v.'], ['behind', 'prep.'], ['believe', 'v.'], ['bell', 'n.'], ['belong', 'v.'], ['below', 'prep.'], ['beside', 'prep.'],
  ['best', 'adj.'], ['better', 'adj.'], ['between', 'prep.'], ['bicycle', 'n.'], ['big', 'adj.'], ['bike', 'n.'], ['bird', 'n.'], ['birthday', 'n.'],
  ['bite', 'v.'], ['black', 'adj.'], ['blanket', 'n.'], ['blind', 'adj.'], ['block', 'n.'], ['blow', 'v.'], ['blue', 'adj.'], ['boat', 'n.'],
  ['body', 'n.'], ['boil', 'v.'], ['book', 'n.'], ['bookstore', 'n.'], ['bored', 'adj.'], ['boring', 'adj.'], ['born', 'adj.'], ['borrow', 'v.'],
  ['boss', 'n.'], ['both', 'adj.'], ['bottle', 'n.'], ['bottom', 'n.'], ['bowl', 'n.'], ['box', 'n.'], ['boy', 'n.'], ['bread', 'n.'],
  ['break', 'v.'], ['breakfast', 'n.'], ['bridge', 'n.'], ['bright', 'adj.'], ['bring', 'v.'], ['brother', 'n.'], ['brown', 'adj.'], ['brush', 'v.'],
  ['build', 'v.'], ['burn', 'v.'], ['bus', 'n.'], ['business', 'n.'], ['busy', 'adj.'], ['but', 'conj.'], ['butter', 'n.'], ['buy', 'v.'],
  ['by', 'prep.'], ['cake', 'n.'], ['call', 'v.'], ['camera', 'n.'], ['camp', 'v.'], ['can', 'aux.'], ['candle', 'n.'], ['candy', 'n.'],
  ['cap', 'n.'], ['car', 'n.'], ['card', 'n.'], ['care', 'v.'], ['careful', 'adj.'], ['carry', 'v.'], ['case', 'n.'], ['cat', 'n.'],
  ['catch', 'v.'], ['celebrate', 'v.'], ['cent', 'n.'], ['center', 'n.'], ['chair', 'n.'], ['chalk', 'n.'], ['chance', 'n.'], ['change', 'v.'],
  ['cheap', 'adj.'], ['cheat', 'v.'], ['check', 'v.'], ['cheer', 'v.'], ['cheese', 'n.'], ['chicken', 'n.'], ['child', 'n.'], ['China', 'n.'],
  ['Chinese', 'adj.'], ['chocolate', 'n.'], ['choose', 'v.'], ['church', 'n.'], ['circle', 'n.'], ['city', 'n.'], ['clap', 'v.'], ['class', 'n.'],
  ['classmate', 'n.'], ['classroom', 'n.'], ['clean', 'adj.'], ['clear', 'adj.'], ['clerk', 'n.'], ['climb', 'v.'], ['clock', 'n.'], ['close', 'v.'],
  ['clothes', 'n.'], ['cloud', 'n.'], ['cloudy', 'adj.'], ['club', 'n.'], ['coat', 'n.'], ['coffee', 'n.'], ['coke', 'n.'], ['cold', 'adj.'],
  ['collect', 'v.'], ['color', 'n.'], ['comb', 'n.'], ['come', 'v.'], ['comfortable', 'adj.'], ['comic', 'n.'], ['common', 'adj.'], ['convenient', 'adj.'],
  ['cook', 'v.'], ['cookie', 'n.'], ['cool', 'adj.'], ['copy', 'v.'], ['corner', 'n.'], ['correct', 'adj.'], ['cost', 'v.'], ['couch', 'n.'],
  ['count', 'v.'], ['country', 'n.'], ['course', 'n.'], ['cousin', 'n.'], ['cover', 'v.'], ['cow', 'n.'], ['crazy', 'adj.'], ['cross', 'v.'],
  ['cry', 'v.'], ['cup', 'n.'], ['cut', 'v.'], ['cute', 'adj.'], ['dance', 'v.'], ['dangerous', 'adj.'], ['dark', 'adj.'], ['date', 'n.'],
  ['daughter', 'n.'], ['day', 'n.'], ['dead', 'adj.'], ['dear', 'adj.'], ['December', 'n.'], ['decide', 'v.'], ['delicious', 'adj.'], ['dentist', 'n.'],
  ['department', 'n.'], ['desk', 'n.'], ['dictionary', 'n.'], ['die', 'v.'], ['different', 'adj.'], ['difficult', 'adj.'], ['dig', 'v.'], ['dinner', 'n.'],
  ['dirty', 'adj.'], ['dish', 'n.'], ['do', 'v.'], ['doctor', 'n.'], ['dog', 'n.'], ['doll', 'n.'], ['dollar', 'n.'], ['door', 'n.'],
  ['dot', 'n.'], ['down', 'adv.'], ['draw', 'v.'], ['drawer', 'n.'], ['dream', 'n.'], ['dress', 'n.'], ['drink', 'v.'], ['drive', 'v.'],
  ['driver', 'n.'], ['drop', 'v.'], ['drum', 'n.'], ['dry', 'adj.'], ['duck', 'n.'], ['during', 'prep.'], ['each', 'adj.'], ['ear', 'n.'],
  ['early', 'adj.'], ['earth', 'n.'], ['east', 'n.'], ['easy', 'adj.'], ['eat', 'v.'], ['egg', 'n.'], ['eight', 'n.'], ['eighteen', 'n.'],
  ['eighty', 'n.'], ['either', 'adv.'], ['elephant', 'n.'], ['eleven', 'n.'], ['else', 'adv.'], ['email', 'n.'], ['end', 'n.'], ['engine', 'n.'],
  ['English', 'n.'], ['enjoy', 'v.'], ['enough', 'adj.'], ['enter', 'v.'], ['erase', 'v.'], ['eraser', 'n.'], ['eve', 'n.'], ['even', 'adv.'],
  ['evening', 'n.'], ['ever', 'adv.'], ['every', 'adj.'], ['everyone', 'pron.'], ['everything', 'pron.'], ['example', 'n.'], ['excellent', 'adj.'], ['except', 'prep.'],
  ['excited', 'adj.'], ['exciting', 'adj.'], ['excuse', 'v.'], ['exercise', 'n.'], ['expensive', 'adj.'], ['experience', 'n.'], ['eye', 'n.'], ['face', 'n.'],
  ['fact', 'n.'], ['factory', 'n.'], ['fall', 'v.'], ['family', 'n.'], ['famous', 'adj.'], ['fan', 'n.'], ['far', 'adv.'], ['farm', 'n.'],
  ['farmer', 'n.'], ['fast', 'adj.'], ['fat', 'adj.'], ['father', 'n.'], ['favorite', 'adj.'], ['February', 'n.'], ['feed', 'v.'], ['feel', 'v.'],
  ['festival', 'n.'], ['fever', 'n.'], ['few', 'adj.'], ['fifteen', 'n.'], ['fifty', 'n.'], ['fight', 'v.'], ['fill', 'v.'], ['finally', 'adv.'],
  ['find', 'v.'], ['fine', 'adj.'], ['finger', 'n.'], ['finish', 'v.'], ['fire', 'n.'], ['first', 'num.'], ['fish', 'n.'], ['fisherman', 'n.'],
  ['five', 'n.'], ['fix', 'v.'], ['flag', 'n.'], ['floor', 'n.'], ['flower', 'n.'], ['flute', 'n.'], ['fly', 'v.'], ['follow', 'v.'],
  ['food', 'n.'], ['foot', 'n.'], ['football', 'n.'], ['for', 'prep.'], ['foreign', 'adj.'], ['foreigner', 'n.'], ['forget', 'v.'], ['fork', 'n.'],
  ['forty', 'n.'], ['four', 'n.'], ['fourteen', 'n.'], ['fox', 'n.'], ['free', 'adj.'], ['fresh', 'adj.'], ['Friday', 'n.'], ['friend', 'n.'],
  ['friendly', 'adj.'], ['frisbee', 'n.'], ['frog', 'n.'], ['from', 'prep.'], ['front', 'n.'], ['fruit', 'n.'], ['full', 'adj.'], ['fun', 'n.'],
  ['funny', 'adj.'], ['future', 'n.'], ['game', 'n.'], ['garbage', 'n.'], ['garden', 'n.'], ['gas', 'n.'], ['gate', 'n.'], ['get', 'v.'],
  ['gift', 'n.'], ['girl', 'n.'], ['give', 'v.'], ['glad', 'adj.'], ['glass', 'n.'], ['glasses', 'n.'], ['glove', 'n.'], ['glue', 'n.'],
  ['go', 'v.'], ['goat', 'n.'], ['good', 'adj.'], ['goodbye', 'interj.'], ['goose', 'n.'], ['grade', 'n.'], ['gram', 'n.'], ['grandfather', 'n.'],
  ['grandmother', 'n.'], ['grape', 'n.'], ['grass', 'n.'], ['gray', 'adj.'], ['great', 'adj.'], ['green', 'adj.'], ['ground', 'n.'], ['group', 'n.'],
  ['grow', 'v.'], ['guava', 'n.'], ['guess', 'v.'], ['guitar', 'n.'], ['gym', 'n.'], ['habit', 'n.'], ['hair', 'n.'], ['half', 'n.'],
  ['ham', 'n.'], ['hamburger', 'n.'], ['hand', 'n.'], ['handsome', 'adj.'], ['hang', 'v.'], ['happen', 'v.'], ['happy', 'adj.'], ['hard', 'adj.'],
  ['hard-working', 'adj.'], ['hat', 'n.'], ['hate', 'v.'], ['have', 'v.'], ['he', 'pron.'], ['head', 'n.'], ['headache', 'n.'], ['health', 'n.'],
  ['healthy', 'adj.'], ['hear', 'v.'], ['heart', 'n.'], ['heat', 'n.'], ['heavy', 'adj.'], ['hello', 'interj.'], ['help', 'v.'], ['helpful', 'adj.'],
  ['hen', 'n.'], ['her', 'pron.'], ['here', 'adv.'], ['hero', 'n.'], ['hers', 'pron.'], ['herself', 'pron.'], ['hey', 'interj.'], ['hi', 'interj.'],
  ['hide', 'v.'], ['high', 'adj.'], ['hike', 'v.'], ['hill', 'n.'], ['him', 'pron.'], ['himself', 'pron.'], ['history', 'n.'], ['hit', 'v.'],
  ['hobby', 'n.'], ['hold', 'v.'], ['holiday', 'n.'], ['home', 'n.'], ['homework', 'n.'], ['honest', 'adj.'], ['hope', 'v.'], ['horse', 'n.'],
  ['hospital', 'n.'], ['hot', 'adj.'], ['hot dog', 'n.'], ['hotel', 'n.'], ['hour', 'n.'], ['house', 'n.'], ['housewife', 'n.'], ['how', 'adv.'],
  ['however', 'adv.'], ['hundred', 'n.'], ['hungry', 'adj.'], ['hurry', 'v.'], ['hurt', 'v.'], ['husband', 'n.'], ['I', 'pron.'], ['ice', 'n.'],
  ['ice cream', 'n.'], ['idea', 'n.'], ['if', 'conj.'], ['important', 'adj.'], ['in', 'prep.'], ['inside', 'prep.'], ['inspire', 'v.'], ['interest', 'n.'],
  ['interested', 'adj.'], ['interesting', 'adj.'], ['internet', 'n.'], ['into', 'prep.'], ['invent', 'v.'], ['invite', 'v.'], ['iron', 'n.'], ['is', 'v.'],
  ['island', 'n.'], ['it', 'pron.'], ['its', 'pron.'], ['itself', 'pron.'], ['jacket', 'n.'], ['January', 'n.'], ['jeans', 'n.'], ['job', 'n.'],
  ['join', 'v.'], ['joy', 'n.'], ['juice', 'n.'], ['July', 'n.'], ['jump', 'v.'], ['June', 'n.'], ['junior', 'adj.'], ['just', 'adv.'],
  ['kangaroo', 'n.'], ['keep', 'v.'], ['key', 'n.'], ['kick', 'v.'], ['kid', 'n.'], ['kill', 'v.'], ['kilogram', 'n.'], ['kilometer', 'n.'],
  ['kind', 'adj.'], ['king', 'n.'], ['kiss', 'v.'], ['kitchen', 'n.'], ['kite', 'n.'], ['kitten', 'n.'], ['knee', 'n.'], ['knife', 'n.'],
  ['knock', 'v.'], ['know', 'v.'], ['knowledge', 'n.'], ['koala', 'n.'], ['lady', 'n.'], ['lake', 'n.'], ['lamp', 'n.'], ['land', 'n.'],
  ['language', 'n.'], ['large', 'adj.'], ['last', 'adj.'], ['late', 'adj.'], ['later', 'adv.'], ['laugh', 'v.'], ['lazy', 'adj.'], ['lead', 'v.'],
  ['leader', 'n.'], ['learn', 'v.'], ['least', 'adv.'], ['leave', 'v.'], ['left', 'adj.'], ['leg', 'n.'], ['lemon', 'n.'], ['lend', 'v.'],
  ['less', 'adj.'], ['lesson', 'n.'], ['let', 'v.'], ['letter', 'n.'], ['lettuce', 'n.'], ['level', 'n.'], ['library', 'n.'], ['lie', 'v.'],
  ['life', 'n.'], ['light', 'n.'], ['like', 'v.'], ['line', 'n.'], ['lion', 'n.'], ['lip', 'n.'], ['list', 'n.'], ['listen', 'v.'],
  ['little', 'adj.'], ['live', 'v.'], ['living room', 'n.'], ['lonely', 'adj.'], ['long', 'adj.'], ['look', 'v.'], ['lose', 'v.'], ['loud', 'adj.'],
  ['love', 'v.'], ['lovely', 'adj.'], ['low', 'adj.'], ['lucky', 'adj.'], ['lunch', 'n.'], ['machine', 'n.'], ['mad', 'adj.'], ['magic', 'n.'],
  ['mail', 'n.'], ['mailman', 'n.'], ['make', 'v.'], ['man', 'n.'], ['many', 'adj.'], ['map', 'n.'], ['March', 'n.'], ['mark', 'n.'],
  ['market', 'n.'], ['marry', 'v.'], ['math', 'n.'], ['matter', 'n.'], ['May', 'n.'], ['maybe', 'adv.'], ['me', 'pron.'], ['meal', 'n.'],
  ['mean', 'v.'], ['meat', 'n.'], ['medicine', 'n.'], ['medium', 'adj.'], ['meet', 'v.'], ['meeting', 'n.'], ['menu', 'n.'], ['message', 'n.'],
  ['meter', 'n.'], ['middle', 'n.'], ['midnight', 'n.'], ['milk', 'n.'], ['million', 'n.'], ['mind', 'n.'], ['mine', 'pron.'], ['minute', 'n.'],
  ['miss', 'v.'], ['mistake', 'n.'], ['modern', 'adj.'], ['moment', 'n.'], ['Monday', 'n.'], ['money', 'n.'], ['monkey', 'n.'], ['monster', 'n.'],
  ['month', 'n.'], ['moon', 'n.'], ['more', 'adj.'], ['morning', 'n.'], ['mop', 'v.'], ['most', 'adj.'], ['mother', 'n.'], ['motorcycle', 'n.'],
  ['mountain', 'n.'], ['mouse', 'n.'], ['mouth', 'n.'], ['move', 'v.'], ['movie', 'n.'], ['Mr.', 'n.'], ['Mrs.', 'n.'], ['Ms.', 'n.'],
  ['much', 'adj.'], ['mud', 'n.'], ['museum', 'n.'], ['music', 'n.'], ['musician', 'n.'], ['must', 'aux.'], ['my', 'pron.'], ['myself', 'pron.'],
  ['nail', 'n.'], ['name', 'n.'], ['national', 'adj.'], ['nature', 'n.'], ['near', 'prep.'], ['neck', 'n.'], ['need', 'v.'], ['neighbor', 'n.'],
  ['neither', 'adv.'], ['nervous', 'adj.'], ['nest', 'n.'], ['net', 'n.'], ['never', 'adv.'], ['new', 'adj.'], ['news', 'n.'], ['next', 'adj.'],
  ['nice', 'adj.'], ['night', 'n.'], ['nine', 'n.'], ['nineteen', 'n.'], ['ninety', 'n.'], ['no', 'adj.'], ['nobody', 'pron.'], ['nod', 'v.'],
  ['noise', 'n.'], ['noodles', 'n.'], ['noon', 'n.'], ['north', 'n.'], ['nose', 'n.'], ['not', 'adv.'], ['notebook', 'n.'], ['nothing', 'pron.'],
  ['notice', 'v.'], ['novel', 'n.'], ['November', 'n.'], ['now', 'adv.'], ['number', 'n.'], ['nurse', 'n.'], ['o\'clock', 'adv.'], ['October', 'n.'],
  ['of', 'prep.'], ['off', 'prep.'], ['office', 'n.'], ['officer', 'n.'], ['often', 'adv.'], ['oil', 'n.'], ['OK', 'adj.'], ['old', 'adj.'],
  ['on', 'prep.'], ['once', 'adv.'], ['one', 'n.'], ['oneself', 'pron.'], ['only', 'adv.'], ['open', 'v.'], ['or', 'conj.'], ['orange', 'n.'],
  ['order', 'n.'], ['other', 'adj.'], ['our', 'pron.'], ['ours', 'pron.'], ['ourselves', 'pron.'], ['out', 'adv.'], ['outside', 'prep.'], ['over', 'prep.'],
  ['own', 'adj.'], ['pack', 'v.'], ['package', 'n.'], ['page', 'n.'], ['paint', 'v.'], ['pair', 'n.'], ['pants', 'n.'], ['papaya', 'n.'],
  ['paper', 'n.'], ['parent', 'n.'], ['park', 'n.'], ['part', 'n.'], ['party', 'n.'], ['pass', 'v.'], ['past', 'n.'], ['paste', 'v.'],
  ['pay', 'v.'], ['PE', 'n.'], ['pear', 'n.'], ['pen', 'n.'], ['pencil', 'n.'], ['people', 'n.'], ['percent', 'n.'], ['person', 'n.'],
  ['pet', 'n.'], ['phone', 'n.'], ['photo', 'n.'], ['piano', 'n.'], ['pick', 'v.'], ['picnic', 'n.'], ['picture', 'n.'], ['pie', 'n.'],
  ['piece', 'n.'], ['pig', 'n.'], ['pin', 'n.'], ['pink', 'adj.'], ['pipe', 'n.'], ['pizza', 'n.'], ['place', 'n.'], ['plan', 'n.'],
  ['plane', 'n.'], ['plant', 'n.'], ['plate', 'n.'], ['play', 'v.'], ['player', 'n.'], ['playground', 'n.'], ['please', 'v.'], ['pleasure', 'n.'],
  ['pocket', 'n.'], ['point', 'n.'], ['police', 'n.'], ['polite', 'adj.'], ['pond', 'n.'], ['pool', 'n.'], ['poor', 'adj.'], ['popcorn', 'n.'],
  ['popular', 'adj.'], ['pork', 'n.'], ['possible', 'adj.'], ['post office', 'n.'], ['postcard', 'n.'], ['pot', 'n.'], ['potato', 'n.'], ['pound', 'n.'],
  ['power', 'n.'], ['practice', 'n.'], ['praise', 'v.'], ['pray', 'v.'], ['prepare', 'v.'], ['present', 'n.'], ['pretty', 'adj.'], ['price', 'n.'],
  ['prince', 'n.'], ['princess', 'n.'], ['prize', 'n.'], ['problem', 'n.'], ['program', 'n.'], ['proud', 'adj.'], ['public', 'adj.'], ['pull', 'v.'],
  ['pumpkin', 'n.'], ['puppy', 'n.'], ['purple', 'adj.'], ['push', 'v.'], ['put', 'v.'], ['queen', 'n.'], ['question', 'n.'], ['quick', 'adj.'],
  ['quiet', 'adj.'], ['quiz', 'n.'], ['rabbit', 'n.'], ['race', 'n.'], ['radio', 'n.'], ['railway', 'n.'], ['rain', 'n.'], ['rainbow', 'n.'],
  ['rainy', 'adj.'], ['raise', 'v.'], ['rat', 'n.'], ['reach', 'v.'], ['read', 'v.'], ['ready', 'adj.'], ['real', 'adj.'], ['really', 'adv.'],
  ['reason', 'n.'], ['receive', 'v.'], ['record', 'n.'], ['red', 'adj.'], ['remember', 'v.'], ['repeat', 'v.'], ['report', 'n.'], ['reporter', 'n.'],
  ['rest', 'n.'], ['restaurant', 'n.'], ['restroom', 'n.'], ['result', 'n.'], ['rice', 'n.'], ['rich', 'adj.'], ['ride', 'v.'], ['right', 'adj.'],
  ['ring', 'n.'], ['river', 'n.'], ['road', 'n.'], ['robot', 'n.'], ['rock', 'n.'], ['roll', 'v.'], ['roller skate', 'n.'], ['roof', 'n.'],
  ['room', 'n.'], ['root', 'n.'], ['rope', 'n.'], ['rose', 'n.'], ['round', 'adj.'], ['row', 'n.'], ['rule', 'n.'], ['ruler', 'n.'],
  ['run', 'v.'], ['sad', 'adj.'], ['safe', 'adj.'], ['salad', 'n.'], ['sale', 'n.'], ['salt', 'n.'], ['same', 'adj.'], ['sandwich', 'n.'],
  ['Saturday', 'n.'], ['save', 'v.'], ['say', 'v.'], ['scared', 'adj.'], ['school', 'n.'], ['science', 'n.'], ['scientist', 'n.'], ['scooter', 'n.'],
  ['score', 'n.'], ['screen', 'n.'], ['sea', 'n.'], ['season', 'n.'], ['seat', 'n.'], ['second', 'num.'], ['secret', 'n.'], ['see', 'v.'],
  ['seed', 'n.'], ['seesaw', 'n.'], ['seldom', 'adv.'], ['sell', 'v.'], ['send', 'v.'], ['senior', 'adj.'], ['sentence', 'n.'], ['September', 'n.'],
  ['serious', 'adj.'], ['set', 'v.'], ['seven', 'n.'], ['seventeen', 'n.'], ['seventy', 'n.'], ['several', 'adj.'], ['shake', 'v.'], ['shall', 'aux.'],
  ['shape', 'n.'], ['share', 'v.'], ['shark', 'n.'], ['sharp', 'adj.'], ['she', 'pron.'], ['sheep', 'n.'], ['shine', 'v.'], ['ship', 'n.'],
  ['shirt', 'n.'], ['shoe', 'n.'], ['shop', 'n.'], ['shopkeeper', 'n.'], ['short', 'adj.'], ['shorts', 'n.'], ['should', 'aux.'], ['shoulder', 'n.'],
  ['shout', 'v.'], ['show', 'v.'], ['shower', 'n.'], ['shut', 'v.'], ['shy', 'adj.'], ['sick', 'adj.'], ['side', 'n.'], ['sidewalk', 'n.'],
  ['sight', 'n.'], ['sign', 'n.'], ['simple', 'adj.'], ['since', 'prep.'], ['sing', 'v.'], ['singer', 'n.'], ['sir', 'n.'], ['sister', 'n.'],
  ['sit', 'v.'], ['six', 'n.'], ['sixteen', 'n.'], ['sixty', 'n.'], ['size', 'n.'], ['skate', 'v.'], ['skirt', 'n.'], ['sky', 'n.'],
  ['sleep', 'v.'], ['slide', 'n.'], ['slim', 'adj.'], ['slow', 'adj.'], ['small', 'adj.'], ['smart', 'adj.'], ['smell', 'v.'], ['smile', 'v.'],
  ['smoke', 'n.'], ['snack', 'n.'], ['snake', 'n.'], ['snow', 'n.'], ['snowman', 'n.'], ['snowy', 'adj.'], ['so', 'adv.'], ['soap', 'n.'],
  ['soccer', 'n.'], ['socks', 'n.'], ['sofa', 'n.'], ['soldier', 'n.'], ['some', 'adj.'], ['someone', 'pron.'], ['something', 'pron.'], ['sometimes', 'adv.'],
  ['somewhere', 'adv.'], ['son', 'n.'], ['song', 'n.'], ['soon', 'adv.'], ['sore', 'adj.'], ['sorry', 'adj.'], ['sound', 'n.'], ['soup', 'n.'],
  ['sour', 'adj.'], ['south', 'n.'], ['space', 'n.'], ['spaghetti', 'n.'], ['speak', 'v.'], ['speaker', 'n.'], ['special', 'adj.'], ['spell', 'v.'],
  ['spend', 'v.'], ['spider', 'n.'], ['spoon', 'n.'], ['sport', 'n.'], ['spring', 'n.'], ['square', 'n.'], ['stairs', 'n.'], ['stamp', 'n.'],
  ['stand', 'v.'], ['star', 'n.'], ['start', 'v.'], ['station', 'n.'], ['stay', 'v.'], ['steak', 'n.'], ['steal', 'v.'], ['step', 'n.'],
  ['stick', 'n.'], ['still', 'adv.'], ['stomach', 'n.'], ['stomachache', 'n.'], ['stop', 'v.'], ['store', 'n.'], ['storm', 'n.'], ['story', 'n.'],
  ['straight', 'adj.'], ['strange', 'adj.'], ['stranger', 'n.'], ['straw', 'n.'], ['strawberry', 'n.'], ['street', 'n.'], ['strong', 'adj.'], ['student', 'n.'],
  ['study', 'v.'], ['stupid', 'adj.'], ['subject', 'n.'], ['successful', 'adj.'], ['sugar', 'n.'], ['summer', 'n.'], ['sun', 'n.'], ['Sunday', 'n.'],
  ['sunny', 'adj.'], ['supermarket', 'n.'], ['supper', 'n.'], ['sure', 'adj.'], ['surf', 'v.'], ['surprise', 'n.'], ['surprised', 'adj.'], ['sweater', 'n.'],
  ['sweet', 'adj.'], ['swim', 'v.'], ['swing', 'n.'], ['table', 'n.'], ['tail', 'n.'], ['Taiwan', 'n.'], ['take', 'v.'], ['talent', 'n.'],
  ['talk', 'v.'], ['tall', 'adj.'], ['tape', 'n.'], ['taste', 'v.'], ['taxi', 'n.'], ['tea', 'n.'], ['teach', 'v.'], ['teacher', 'n.'],
  ['team', 'n.'], ['teenager', 'n.'], ['telephone', 'n.'], ['television', 'n.'], ['tell', 'v.'], ['temple', 'n.'], ['ten', 'n.'], ['tennis', 'n.'],
  ['terrible', 'adj.'], ['test', 'n.'], ['than', 'prep.'], ['thank', 'v.'], ['that', 'pron.'], ['the', 'art.'], ['theater', 'n.'], ['their', 'pron.'],
  ['theirs', 'pron.'], ['them', 'pron.'], ['themselves', 'pron.'], ['then', 'adv.'], ['there', 'adv.'], ['these', 'pron.'], ['they', 'pron.'], ['thick', 'adj.'],
  ['thin', 'adj.'], ['thing', 'n.'], ['think', 'v.'], ['third', 'num.'], ['thirsty', 'adj.'], ['thirteen', 'n.'], ['thirty', 'n.'], ['this', 'pron.'],
  ['those', 'pron.'], ['though', 'conj.'], ['thought', 'n.'], ['thousand', 'n.'], ['three', 'n.'], ['throat', 'n.'], ['through', 'prep.'], ['throw', 'v.'],
  ['Thursday', 'n.'], ['ticket', 'n.'], ['tidy', 'adj.'], ['tie', 'n.'], ['tiger', 'n.'], ['time', 'n.'], ['tired', 'adj.'], ['to', 'prep.'],
  ['toast', 'n.'], ['today', 'n.'], ['toe', 'n.'], ['together', 'adv.'], ['tomato', 'n.'], ['tomorrow', 'n.'], ['tonight', 'n.'], ['too', 'adv.'],
  ['tooth', 'n.'], ['toothache', 'n.'], ['toothbrush', 'n.'], ['top', 'n.'], ['total', 'adj.'], ['touch', 'v.'], ['towel', 'n.'], ['town', 'n.'],
  ['toy', 'n.'], ['traffic', 'n.'], ['train', 'n.'], ['trash', 'n.'], ['travel', 'v.'], ['treasure', 'n.'], ['treat', 'v.'], ['tree', 'n.'],
  ['trick', 'n.'], ['trip', 'n.'], ['trouble', 'n.'], ['truck', 'n.'], ['true', 'adj.'], ['try', 'v.'], ['T-shirt', 'n.'], ['tub', 'n.'],
  ['Tuesday', 'n.'], ['turn', 'v.'], ['turtle', 'n.'], ['twelve', 'n.'], ['twenty', 'n.'], ['two', 'n.'], ['type', 'n.'], ['typhoon', 'n.'],
  ['ugly', 'adj.'], ['umbrella', 'n.'], ['uncle', 'n.'], ['under', 'prep.'], ['understand', 'v.'], ['uniform', 'n.'], ['unit', 'n.'], ['until', 'prep.'],
  ['up', 'adv.'], ['upon', 'prep.'], ['us', 'pron.'], ['use', 'v.'], ['useful', 'adj.'], ['vacation', 'n.'], ['vegetable', 'n.'], ['very', 'adv.'],
  ['vest', 'n.'], ['video', 'n.'], ['violin', 'n.'], ['visit', 'v.'], ['visitor', 'n.'], ['voice', 'n.'], ['wait', 'v.'], ['waiter', 'n.'],
  ['waitress', 'n.'], ['wake', 'v.'], ['walk', 'v.'], ['wall', 'n.'], ['wallet', 'n.'], ['want', 'v.'], ['warm', 'adj.'], ['wash', 'v.'],
  ['waste', 'v.'], ['watch', 'v.'], ['water', 'n.'], ['watermelon', 'n.'], ['wave', 'v.'], ['way', 'n.'], ['we', 'pron.'], ['weak', 'adj.'],
  ['wear', 'v.'], ['weather', 'n.'], ['Wednesday', 'n.'], ['week', 'n.'], ['weekend', 'n.'], ['welcome', 'adj.'], ['well', 'adv.'], ['west', 'n.'],
  ['wet', 'adj.'], ['whale', 'n.'], ['what', 'pron.'], ['wheel', 'n.'], ['when', 'adv.'], ['where', 'adv.'], ['whether', 'conj.'], ['which', 'pron.'],
  ['while', 'conj.'], ['white', 'adj.'], ['who', 'pron.'], ['whose', 'pron.'], ['why', 'adv.'], ['wide', 'adj.'], ['wife', 'n.'], ['wild', 'adj.'],
  ['will', 'aux.'], ['win', 'v.'], ['wind', 'n.'], ['window', 'n.'], ['windy', 'adj.'], ['wine', 'n.'], ['winner', 'n.'], ['winter', 'n.'],
  ['wise', 'adj.'], ['wish', 'v.'], ['with', 'prep.'], ['without', 'prep.'], ['woman', 'n.'], ['wonderful', 'adj.'], ['wood', 'n.'], ['word', 'n.'],
  ['work', 'v.'], ['worker', 'n.'], ['world', 'n.'], ['worry', 'v.'], ['would', 'aux.'], ['write', 'v.'], ['writer', 'n.'], ['wrong', 'adj.'],
  ['yard', 'n.'], ['year', 'n.'], ['yellow', 'adj.'], ['yes', 'adv.'], ['yesterday', 'n.'], ['yet', 'adv.'], ['you', 'pron.'], ['young', 'adj.'],
  ['your', 'pron.'], ['yours', 'pron.'], ['yourself', 'pron.'], ['yourselves', 'pron.'], ['yummy', 'adj.'], ['zebra', 'n.'], ['zero', 'n.'], ['zoo', 'n.']
]

// 800 Extension Words
const extension800Words: [string, string][] = [
  ['ability', 'n.'], ['aboard', 'prep.'], ['abroad', 'adv.'], ['absent', 'adj.'], ['accept', 'v.'], ['accident', 'n.'], ['achieve', 'v.'], ['active', 'adj.'],
  ['activity', 'n.'], ['ad', 'n.'], ['address', 'n.'], ['admire', 'v.'], ['admit', 'v.'], ['adopt', 'v.'], ['adult', 'n.'], ['advance', 'v.'],
  ['advantage', 'n.'], ['adventure', 'n.'], ['advertisement', 'n.'], ['advice', 'n.'], ['advise', 'v.'], ['affect', 'v.'], ['afford', 'v.'], ['agreeable', 'adj.'],
  ['aim', 'n.'], ['airline', 'n.'], ['alarm', 'n.'], ['album', 'n.'], ['alike', 'adj.'], ['alive', 'adj.'], ['allow', 'v.'], ['aloud', 'adv.'],
  ['alphabet', 'n.'], ['amount', 'n.'], ['ancient', 'adj.'], ['angel', 'n.'], ['anger', 'n.'], ['ankle', 'n.'], ['announce', 'v.'], ['antelope', 'n.'],
  ['anxious', 'adj.'], ['anybody', 'pron.'], ['anyhow', 'adv.'], ['anyway', 'adv.'], ['anywhere', 'adv.'], ['apology', 'n.'], ['appreciate', 'v.'], ['area', 'n.'],
  ['argue', 'v.'], ['argument', 'n.'], ['army', 'n.'], ['arrange', 'v.'], ['arrest', 'v.'], ['article', 'n.'], ['artist', 'n.'], ['ashamed', 'adj.'],
  ['aside', 'adv.'], ['assistant', 'n.'], ['attack', 'v.'], ['attend', 'v.'], ['attention', 'n.'], ['attitude', 'n.'], ['attract', 'v.'], ['audience', 'n.'],
  ['author', 'n.'], ['automatic', 'adj.'], ['available', 'adj.'], ['average', 'adj.'], ['avoid', 'v.'], ['award', 'n.'], ['aware', 'adj.'], ['awful', 'adj.'],
  ['background', 'n.'], ['bacon', 'n.'], ['bake', 'v.'], ['bamboo', 'n.'], ['bandage', 'n.'], ['bare', 'adj.'], ['bargain', 'n.'], ['bark', 'v.'],
  ['basement', 'n.'], ['basic', 'adj.'], ['basis', 'n.'], ['bean', 'n.'], ['beard', 'n.'], ['beat', 'v.'], ['beg', 'v.'], ['beginner', 'n.'],
  ['behave', 'v.'], ['behavior', 'n.'], ['belt', 'n.'], ['bench', 'n.'], ['bend', 'v.'], ['benefit', 'n.'], ['beyond', 'prep.'], ['bill', 'n.'],
  ['biology', 'n.'], ['bit', 'n.'], ['bitter', 'adj.'], ['blame', 'v.'], ['bleed', 'v.'], ['bless', 'v.'], ['blouse', 'n.'], ['board', 'n.'],
  ['boast', 'v.'], ['bomb', 'n.'], ['bone', 'n.'], ['border', 'n.'], ['bother', 'v.'], ['bow', 'v.'], ['brain', 'n.'], ['brake', 'n.'],
  ['branch', 'n.'], ['brave', 'adj.'], ['breath', 'n.'], ['breathe', 'v.'], ['breeze', 'n.'], ['brick', 'n.'], ['brief', 'adj.'], ['broad', 'adj.'],
  ['broadcast', 'v.'], ['bucket', 'n.'], ['bullet', 'n.'], ['bunch', 'n.'], ['bundle', 'n.'], ['burden', 'n.'], ['burst', 'v.'], ['button', 'n.'],
  ['cabbage', 'n.'], ['cabin', 'n.'], ['cable', 'n.'], ['cafeteria', 'n.'], ['calendar', 'n.'], ['calm', 'adj.'], ['campus', 'n.'], ['cancel', 'v.'],
  ['cancer', 'n.'], ['captain', 'n.'], ['career', 'n.'], ['carpenter', 'n.'], ['carriage', 'n.'], ['cash', 'n.'], ['castle', 'n.'], ['casual', 'adj.'],
  ['cattle', 'n.'], ['cause', 'n.'], ['ceiling', 'n.'], ['central', 'adj.'], ['century', 'n.'], ['cereal', 'n.'], ['certain', 'adj.'], ['challenge', 'n.'],
  ['champion', 'n.'], ['channel', 'n.'], ['chapter', 'n.'], ['character', 'n.'], ['charge', 'n.'], ['chart', 'n.'], ['chase', 'v.'], ['chat', 'v.'],
  ['cheek', 'n.'], ['chemical', 'adj.'], ['chemist', 'n.'], ['chemistry', 'n.'], ['chest', 'n.'], ['chew', 'v.'], ['chief', 'n.'], ['childhood', 'n.'],
  ['chimney', 'n.'], ['chin', 'n.'], ['choice', 'n.'], ['chopstick', 'n.'], ['circus', 'n.'], ['citizen', 'n.'], ['claim', 'v.'], ['classic', 'adj.'],
  ['classical', 'adj.'], ['climate', 'n.'], ['closet', 'n.'], ['cloth', 'n.'], ['coach', 'n.'], ['coast', 'n.'], ['cockroach', 'n.'], ['coin', 'n.'],
  ['collar', 'n.'], ['colleague', 'n.'], ['collection', 'n.'], ['college', 'n.'], ['colony', 'n.'], ['column', 'n.'], ['combine', 'v.'], ['comfort', 'n.'],
  ['command', 'v.'], ['commercial', 'adj.'], ['committee', 'n.'], ['communicate', 'v.'], ['community', 'n.'], ['companion', 'n.'], ['company', 'n.'], ['compare', 'v.'],
  ['compete', 'v.'], ['competition', 'n.'], ['complain', 'v.'], ['complete', 'adj.'], ['complex', 'adj.'], ['concentrate', 'v.'], ['concept', 'n.'], ['concern', 'n.'],
  ['conclude', 'v.'], ['conclusion', 'n.'], ['condition', 'n.'], ['conduct', 'v.'], ['confident', 'adj.'], ['confirm', 'v.'], ['conflict', 'n.'], ['confuse', 'v.'],
  ['congratulate', 'v.'], ['connect', 'v.'], ['conscious', 'adj.'], ['consider', 'v.'], ['contact', 'v.'], ['contain', 'v.'], ['continent', 'n.'], ['continue', 'v.'],
  ['contract', 'n.'], ['control', 'v.'], ['conversation', 'n.'], ['convince', 'v.'], ['cooperate', 'v.'], ['courage', 'n.'], ['court', 'n.'], ['crab', 'n.'],
  ['cradle', 'n.'], ['craft', 'n.'], ['crash', 'v.'], ['crawl', 'v.'], ['create', 'v.'], ['credit', 'n.'], ['crew', 'n.'], ['crime', 'n.'],
  ['criminal', 'n.'], ['crisp', 'adj.'], ['crop', 'n.'], ['crowd', 'n.'], ['crowded', 'adj.'], ['crown', 'n.'], ['cruel', 'adj.'], ['crush', 'v.'],
  ['culture', 'n.'], ['cure', 'v.'], ['curious', 'adj.'], ['curtain', 'n.'], ['cushion', 'n.'], ['custom', 'n.'], ['customer', 'n.'], ['daily', 'adj.'],
  ['damage', 'n.'], ['danger', 'n.'], ['dare', 'v.'], ['data', 'n.'], ['dawn', 'n.'], ['deaf', 'adj.'], ['deal', 'v.'], ['debate', 'n.'],
  ['debt', 'n.'], ['decision', 'n.'], ['decorate', 'v.'], ['decrease', 'v.'], ['deep', 'adj.'], ['deer', 'n.'], ['defeat', 'v.'], ['defend', 'v.'],
  ['defense', 'n.'], ['degree', 'n.'], ['delay', 'v.'], ['deliver', 'v.'], ['demand', 'v.'], ['demonstrate', 'v.'], ['deny', 'v.'], ['depend', 'v.'],
  ['describe', 'v.'], ['desert', 'n.'], ['design', 'n.'], ['desire', 'n.'], ['destroy', 'v.'], ['detail', 'n.'], ['determine', 'v.'], ['develop', 'v.'],
  ['device', 'n.'], ['dialogue', 'n.'], ['diamond', 'n.'], ['diary', 'n.'], ['differ', 'v.'], ['difference', 'n.'], ['difficulty', 'n.'], ['direct', 'adj.'],
  ['direction', 'n.'], ['director', 'n.'], ['disadvantage', 'n.'], ['disagree', 'v.'], ['disappear', 'v.'], ['disappoint', 'v.'], ['disaster', 'n.'], ['discipline', 'n.'],
  ['discover', 'v.'], ['discovery', 'n.'], ['discuss', 'v.'], ['discussion', 'n.'], ['disease', 'n.'], ['dismiss', 'v.'], ['distance', 'n.'], ['distant', 'adj.'],
  ['distinguish', 'v.'], ['distribute', 'v.'], ['district', 'n.'], ['divide', 'v.'], ['division', 'n.'], ['document', 'n.'], ['dolphin', 'n.'], ['donkey', 'n.'],
  ['doubt', 'n.'], ['dove', 'n.'], ['downtown', 'adv.'], ['drag', 'v.'], ['dragon', 'n.'], ['drama', 'n.'], ['dramatic', 'adj.'], ['drastic', 'adj.'],
  ['drawer', 'n.'], ['dreadful', 'adj.'], ['drift', 'v.'], ['drill', 'n.'], ['drown', 'v.'], ['drug', 'n.'], ['drugstore', 'n.'], ['dumb', 'adj.'],
  ['dump', 'v.'], ['dust', 'n.'], ['duty', 'n.'], ['eager', 'adj.'], ['eagle', 'n.'], ['earn', 'v.'], ['earnest', 'adj.'], ['earthquake', 'n.'],
  ['ease', 'n.'], ['echo', 'n.'], ['economic', 'adj.'], ['economy', 'n.'], ['edge', 'n.'], ['educate', 'v.'], ['education', 'n.'], ['effect', 'n.'],
  ['effort', 'n.'], ['election', 'n.'], ['electric', 'adj.'], ['electricity', 'n.'], ['electronic', 'adj.'], ['element', 'n.'], ['elevator', 'n.'], ['embarrass', 'v.'],
  ['emotion', 'n.'], ['emphasize', 'v.'], ['employ', 'v.'], ['employee', 'n.'], ['employer', 'n.'], ['empty', 'adj.'], ['enable', 'v.'], ['encourage', 'v.'],
  ['energy', 'n.'], ['engage', 'v.'], ['enjoyable', 'adj.'], ['enormous', 'adj.'], ['ensure', 'v.'], ['entertain', 'v.'], ['entire', 'adj.'], ['environment', 'n.'],
  ['envy', 'v.'], ['equal', 'adj.'], ['equipment', 'n.'], ['error', 'n.'], ['escape', 'v.'], ['essay', 'n.'], ['essential', 'adj.'], ['establish', 'v.'],
  ['evaluate', 'v.'], ['event', 'n.'], ['evidence', 'n.'], ['exact', 'adj.'], ['examine', 'v.'], ['example', 'n.'], ['exchange', 'v.'], ['excite', 'v.'],
  ['excitement', 'n.'], ['exist', 'v.'], ['existence', 'n.'], ['exit', 'n.'], ['expect', 'v.'], ['expense', 'n.'], ['expert', 'n.'], ['explain', 'v.'],
  ['explanation', 'n.'], ['explode', 'v.'], ['explore', 'v.'], ['express', 'v.'], ['expression', 'n.'], ['extra', 'adj.'], ['extraordinary', 'adj.'], ['extreme', 'adj.'],
  ['fail', 'v.'], ['failure', 'n.'], ['fair', 'adj.'], ['fairly', 'adv.'], ['faith', 'n.'], ['false', 'adj.'], ['familiar', 'adj.'], ['fancy', 'adj.'],
  ['fantastic', 'adj.'], ['fare', 'n.'], ['farther', 'adv.'], ['fashion', 'n.'], ['fault', 'n.'], ['favor', 'n.'], ['favorable', 'adj.'], ['fear', 'n.'],
  ['feather', 'n.'], ['feature', 'n.'], ['fee', 'n.'], ['female', 'adj.'], ['fence', 'n.'], ['field', 'n.'], ['fierce', 'adj.'], ['figure', 'n.'],
  ['file', 'n.'], ['film', 'n.'], ['final', 'adj.'], ['finance', 'n.'], ['firm', 'adj.'], ['fist', 'n.'], ['fit', 'v.'], ['flame', 'n.'],
  ['flash', 'n.'], ['flat', 'adj.'], ['flavor', 'n.'], ['flee', 'v.'], ['flesh', 'n.'], ['flight', 'n.'], ['float', 'v.'], ['flock', 'n.'],
  ['flood', 'n.'], ['flow', 'v.'], ['flour', 'n.'], ['focus', 'v.'], ['fog', 'n.'], ['foggy', 'adj.'], ['folk', 'n.'], ['fool', 'n.'],
  ['foolish', 'adj.'], ['force', 'n.'], ['forecast', 'n.'], ['forest', 'n.'], ['forever', 'adv.'], ['forgive', 'v.'], ['form', 'n.'], ['formal', 'adj.'],
  ['former', 'adj.'], ['forth', 'adv.'], ['fortune', 'n.'], ['forward', 'adv.'], ['found', 'v.'], ['foundation', 'n.'], ['fountain', 'n.'], ['fragment', 'n.'],
  ['frame', 'n.'], ['frank', 'adj.'], ['freedom', 'n.'], ['freeze', 'v.'], ['frequent', 'adj.'], ['frighten', 'v.'], ['fuel', 'n.'], ['gain', 'v.'],
  ['garage', 'n.'], ['gather', 'v.'], ['general', 'adj.'], ['generous', 'adj.'], ['genius', 'n.'], ['gentle', 'adj.'], ['gentleman', 'n.'], ['gesture', 'n.'],
  ['giant', 'n.'], ['glance', 'v.'], ['global', 'adj.'], ['glory', 'n.'], ['goal', 'n.'], ['god', 'n.'], ['goddess', 'n.'], ['gold', 'n.'],
  ['golden', 'adj.'], ['golf', 'n.'], ['govern', 'v.'], ['government', 'n.'], ['governor', 'n.'], ['gown', 'n.'], ['grace', 'n.'], ['gradual', 'adj.'],
  ['graduate', 'v.'], ['grain', 'n.'], ['grand', 'adj.'], ['grateful', 'adj.'], ['gratitude', 'n.'], ['grave', 'n.'], ['greet', 'v.'], ['greeting', 'n.'],
  ['grocery', 'n.'], ['growth', 'n.'], ['guard', 'n.'], ['guide', 'n.'], ['guilty', 'adj.'], ['gulf', 'n.'], ['gum', 'n.'], ['hall', 'n.'],
  ['handkerchief', 'n.'], ['handle', 'v.'], ['harbor', 'n.'], ['hardly', 'adv.'], ['hardship', 'n.'], ['harm', 'n.'], ['harmful', 'adj.'], ['harvest', 'n.'],
  ['haste', 'n.'], ['hasty', 'adj.'], ['hatred', 'n.'], ['hawk', 'n.'], ['hay', 'n.'], ['heal', 'v.'], ['headline', 'n.'], ['heal', 'v.'],
  ['heavily', 'adv.'], ['height', 'n.'], ['helicopter', 'n.'], ['helmet', 'n.'], ['hence', 'adv.'], ['herd', 'n.'], ['hesitate', 'v.'], ['highway', 'n.'],
  ['hire', 'v.'], ['hollow', 'adj.'], ['honesty', 'n.'], ['honey', 'n.'], ['honor', 'n.'], ['horn', 'n.'], ['horrible', 'adj.'], ['horror', 'n.'],
  ['host', 'n.'], ['hostess', 'n.'], ['household', 'n.'], ['huge', 'adj.'], ['human', 'adj.'], ['humble', 'adj.'], ['humid', 'adj.'], ['humor', 'n.'],
  ['hunger', 'n.'], ['hunt', 'v.'], ['hunter', 'n.'], ['hut', 'n.'], ['hydrogen', 'n.'], ['iceberg', 'n.'], ['ideal', 'adj.'], ['identical', 'adj.'],
  ['identify', 'v.'], ['ignore', 'v.'], ['ill', 'adj.'], ['illness', 'n.'], ['image', 'n.'], ['imagination', 'n.'], ['imagine', 'v.'], ['immediate', 'adj.'],
  ['immense', 'adj.'], ['import', 'v.'], ['importance', 'n.'], ['impress', 'v.'], ['impression', 'n.'], ['improve', 'v.'], ['improvement', 'n.'], ['include', 'v.'],
  ['income', 'n.'], ['increase', 'v.'], ['indeed', 'adv.'], ['independent', 'adj.'], ['indicate', 'v.'], ['industry', 'n.'], ['influence', 'n.'], ['inform', 'v.'],
  ['information', 'n.'], ['initial', 'adj.'], ['injure', 'v.'], ['injury', 'n.'], ['ink', 'n.'], ['innocent', 'adj.'], ['insect', 'n.'], ['insist', 'v.'],
  ['inspect', 'v.'], ['instance', 'n.'], ['instant', 'adj.'], ['instead', 'adv.'], ['instruction', 'n.'], ['instrument', 'n.'], ['insult', 'v.'], ['insurance', 'n.'],
  ['intelligence', 'n.'], ['intelligent', 'adj.'], ['intend', 'v.'], ['intention', 'n.'], ['interrupt', 'v.'], ['interview', 'n.'], ['introduce', 'v.'], ['introduction', 'n.'],
  ['invitation', 'n.'], ['item', 'n.'], ['jail', 'n.'], ['jam', 'n.'], ['jar', 'n.'], ['jaw', 'n.'], ['jealous', 'adj.'], ['jeep', 'n.'],
  ['jelly', 'n.'], ['jet', 'n.'], ['jewel', 'n.'], ['jewelry', 'n.'], ['journal', 'n.'], ['journey', 'n.'], ['judge', 'n.'], ['judgment', 'n.'],
  ['jungle', 'n.'], ['jury', 'n.'], ['justice', 'n.'], ['kangaroo', 'n.'], ['keen', 'adj.'], ['kettle', 'n.'], ['keyboard', 'n.'], ['kneel', 'v.'],
  ['knight', 'n.'], ['knit', 'v.'], ['knot', 'n.'], ['label', 'n.'], ['labor', 'n.'], ['laboratory', 'n.'], ['lace', 'n.'], ['lack', 'n.'],
  ['ladder', 'n.'], ['lamb', 'n.'], ['lane', 'n.'], ['lantern', 'n.'], ['lap', 'n.'], ['lately', 'adv.'], ['latter', 'adj.'], ['laughter', 'n.'],
  ['laundry', 'n.'], ['lawn', 'n.'], ['lawyer', 'n.'], ['lay', 'v.'], ['layer', 'n.'], ['leading', 'adj.'], ['leak', 'v.'], ['lean', 'v.'],
  ['leap', 'v.'], ['leather', 'n.'], ['legal', 'adj.'], ['leisure', 'n.'], ['length', 'n.'], ['leopard', 'n.'], ['lesser', 'adj.'], ['liberty', 'n.'],
  ['librarian', 'n.'], ['license', 'n.'], ['lid', 'n.'], ['lifelong', 'adj.'], ['lift', 'v.'], ['lightning', 'n.'], ['likely', 'adj.'], ['limit', 'n.'],
  ['limb', 'n.'], ['liquid', 'n.'], ['literature', 'n.'], ['lively', 'adj.'], ['liver', 'n.'], ['load', 'n.'], ['loaf', 'n.'], ['loan', 'n.'],
  ['local', 'adj.'], ['locate', 'v.'], ['location', 'n.'], ['lock', 'n.'], ['log', 'n.'], ['logic', 'n.'], ['logical', 'adj.'], ['loose', 'adj.'],
  ['lord', 'n.'], ['loss', 'n.'], ['lottery', 'n.'], ['lover', 'n.'], ['loyal', 'adj.'], ['luggage', 'n.'], ['lump', 'n.'], ['luxury', 'n.'],
  ['magician', 'n.'], ['magnet', 'n.'], ['magnificent', 'adj.'], ['maid', 'n.'], ['maintain', 'v.'], ['major', 'adj.'], ['majority', 'n.'], ['male', 'adj.'],
  ['manage', 'v.'], ['management', 'n.'], ['manager', 'n.'], ['mankind', 'n.'], ['manner', 'n.'], ['manual', 'adj.'], ['manufacture', 'v.'], ['marble', 'n.'],
  ['march', 'v.'], ['marine', 'adj.'], ['marvelous', 'adj.'], ['mask', 'n.'], ['mass', 'n.'], ['master', 'n.'], ['match', 'n.'], ['material', 'n.'],
  ['mature', 'adj.'], ['maximum', 'adj.'], ['mayor', 'n.'], ['meadow', 'n.'], ['meaning', 'n.'], ['measure', 'v.'], ['measurement', 'n.'], ['medal', 'n.'],
  ['media', 'n.'], ['medical', 'adj.'], ['melody', 'n.'], ['melt', 'v.'], ['member', 'n.'], ['membership', 'n.'], ['memo', 'n.'], ['memorial', 'n.'],
  ['memory', 'n.'], ['mend', 'v.'], ['mental', 'adj.'], ['mention', 'v.'], ['merchant', 'n.'], ['mercy', 'n.'], ['merely', 'adv.'], ['merit', 'n.'],
  ['merry', 'adj.'], ['metal', 'n.'], ['method', 'n.'], ['microscope', 'n.'], ['microwave', 'n.'], ['military', 'adj.'], ['mineral', 'n.'], ['minimum', 'adj.'],
  ['minister', 'n.'], ['ministry', 'n.'], ['minor', 'adj.'], ['minority', 'n.'], ['miracle', 'n.'], ['misfortune', 'n.'], ['missile', 'n.'], ['mission', 'n.'],
  ['mist', 'n.'], ['mixture', 'n.'], ['mob', 'n.'], ['mobile', 'adj.'], ['model', 'n.'], ['moderate', 'adj.'], ['modest', 'adj.'], ['moisture', 'n.'],
  ['molecule', 'n.'], ['monitor', 'n.'], ['monument', 'n.'], ['mood', 'n.'], ['moral', 'adj.'], ['mosquito', 'n.'], ['motel', 'n.'], ['motto', 'n.'],
  ['mount', 'v.'], ['mourn', 'v.'], ['movement', 'n.'], ['multiple', 'adj.'], ['murder', 'n.'], ['muscle', 'n.'], ['mystery', 'n.'], ['naked', 'adj.'],
  ['napkin', 'n.'], ['narrate', 'v.'], ['narrow', 'adj.'], ['nation', 'n.'], ['nationality', 'n.'], ['native', 'adj.'], ['natural', 'adj.'], ['naval', 'adj.'],
  ['navy', 'n.'], ['neat', 'adj.'], ['necessary', 'adj.'], ['necessity', 'n.'], ['needle', 'n.'], ['neglect', 'v.'], ['negotiate', 'v.'], ['nephew', 'n.'],
  ['nerve', 'n.'], ['net', 'n.'], ['niece', 'n.'], ['nightmare', 'n.'], ['noble', 'adj.'], ['normal', 'adj.'], ['novelty', 'n.'], ['nuclear', 'adj.'],
  ['numerous', 'adj.'], ['nutrient', 'n.'], ['nylon', 'n.'], ['oak', 'n.'], ['obedient', 'adj.'], ['obey', 'v.'], ['object', 'n.'], ['objection', 'n.'],
  ['observe', 'v.'], ['observation', 'n.'], ['obstacle', 'n.'], ['obtain', 'v.'], ['obvious', 'adj.'], ['occasion', 'n.'], ['occasional', 'adj.'], ['occupy', 'v.'],
  ['occur', 'v.'], ['ocean', 'n.'], ['offend', 'v.'], ['offense', 'n.'], ['offensive', 'adj.'], ['offer', 'v.'], ['official', 'adj.'], ['omit', 'v.'],
  ['onion', 'n.'], ['operate', 'v.'], ['operation', 'n.'], ['operator', 'n.'], ['opinion', 'n.'], ['opponent', 'n.'], ['opportunity', 'n.'], ['oppose', 'v.'],
  ['opposite', 'adj.'], ['optimistic', 'adj.'], ['option', 'n.'], ['orbit', 'n.'], ['orchestra', 'n.'], ['ordinary', 'adj.'], ['organ', 'n.'], ['organic', 'adj.'],
  ['organize', 'v.'], ['organization', 'n.'], ['origin', 'n.'], ['original', 'adj.'], ['orphan', 'n.'], ['ought', 'aux.'], ['outcome', 'n.'], ['outline', 'n.'],
  ['output', 'n.'], ['outstanding', 'adj.'], ['oval', 'adj.'], ['overall', 'adj.'], ['overcome', 'v.'], ['overnight', 'adv.'], ['overseas', 'adv.'], ['owe', 'v.'],
  ['owl', 'n.'], ['owner', 'n.'], ['ownership', 'n.'], ['oxygen', 'n.'], ['pace', 'n.'], ['pacific', 'adj.'], ['packet', 'n.'], ['pain', 'n.'],
  ['painful', 'adj.'], ['painter', 'n.'], ['pale', 'adj.'], ['palm', 'n.'], ['pan', 'n.'], ['panel', 'n.'], ['panic', 'n.'], ['parade', 'n.'],
  ['paradise', 'n.'], ['paragraph', 'n.'], ['parallel', 'adj.'], ['parcel', 'n.'], ['pardon', 'v.'], ['parrot', 'n.'], ['partial', 'adj.'], ['particular', 'adj.'],
  ['partner', 'n.'], ['passage', 'n.'], ['passenger', 'n.'], ['passion', 'n.'], ['passport', 'n.'], ['path', 'n.'], ['patience', 'n.'], ['patient', 'adj.'],
  ['patrol', 'n.'], ['pattern', 'n.'], ['pause', 'v.'], ['pave', 'v.'], ['pavement', 'n.'], ['peace', 'n.'], ['peaceful', 'adj.'], ['peach', 'n.'],
  ['peak', 'n.'], ['peanut', 'n.'], ['peculiar', 'adj.'], ['peer', 'n.'], ['penalty', 'n.'], ['penny', 'n.'], ['perform', 'v.'], ['performance', 'n.'],
  ['performer', 'n.'], ['period', 'n.'], ['permanent', 'adj.'], ['permission', 'n.'], ['permit', 'v.'], ['personality', 'n.'], ['persuade', 'v.'], ['pessimistic', 'adj.'],
  ['pest', 'n.'], ['petroleum', 'n.'], ['phase', 'n.'], ['philosophy', 'n.'], ['photograph', 'n.'], ['phrase', 'n.'], ['physical', 'adj.'], ['physician', 'n.'],
  ['physics', 'n.'], ['pianist', 'n.'], ['pile', 'n.'], ['pillow', 'n.'], ['pilot', 'n.'], ['pity', 'n.'], ['plastic', 'n.'], ['platform', 'n.'],
  ['player', 'n.'], ['pleasant', 'adj.'], ['plenty', 'n.'], ['plot', 'n.'], ['plug', 'n.'], ['plumber', 'n.'], ['poem', 'n.'], ['poet', 'n.'],
  ['poetry', 'n.'], ['poison', 'n.'], ['poisonous', 'adj.'], ['pole', 'n.'], ['policy', 'n.'], ['polish', 'v.'], ['political', 'adj.'], ['politician', 'n.'],
  ['politics', 'n.'], ['pollute', 'v.'], ['pollution', 'n.'], ['portion', 'n.'], ['portrait', 'n.'], ['position', 'n.'], ['positive', 'adj.'], ['possess', 'v.'],
  ['possession', 'n.'], ['possibility', 'n.'], ['postal', 'adj.'], ['postpone', 'v.'], ['pour', 'v.'], ['poverty', 'n.'], ['powder', 'n.'], ['practical', 'adj.'],
  ['prayer', 'n.'], ['precious', 'adj.'], ['precise', 'adj.'], ['predict', 'v.'], ['prefer', 'v.'], ['preference', 'n.'], ['pregnant', 'adj.'], ['premise', 'n.'],
  ['presence', 'n.'], ['preserve', 'v.'], ['president', 'n.'], ['press', 'n.'], ['pressure', 'n.'], ['pretend', 'v.'], ['prevent', 'v.'], ['previous', 'adj.'],
  ['priest', 'n.'], ['primary', 'adj.'], ['primitive', 'adj.'], ['principal', 'n.'], ['principle', 'n.'], ['prison', 'n.'], ['prisoner', 'n.'], ['private', 'adj.'],
  ['probable', 'adj.'], ['process', 'n.'], ['produce', 'v.'], ['producer', 'n.'], ['product', 'n.'], ['production', 'n.'], ['profession', 'n.'], ['professional', 'adj.'],
  ['professor', 'n.'], ['profit', 'n.'], ['progress', 'n.'], ['progressive', 'adj.'], ['project', 'n.'], ['promise', 'v.'], ['promote', 'v.'], ['prompt', 'adj.'],
  ['pronounce', 'v.'], ['proof', 'n.'], ['proper', 'adj.'], ['property', 'n.'], ['proposal', 'n.'], ['propose', 'v.'], ['prospect', 'n.'], ['protect', 'v.'],
  ['protection', 'n.'], ['protein', 'n.'], ['protest', 'v.'], ['provide', 'v.'], ['psychology', 'n.'], ['publish', 'v.'], ['publisher', 'n.'], ['pump', 'n.'],
  ['punish', 'v.'], ['punishment', 'n.'], ['pupil', 'n.'], ['pure', 'adj.'], ['purpose', 'n.'], ['pursue', 'v.'], ['puzzle', 'n.'], ['qualification', 'n.'],
  ['qualify', 'v.'], ['quality', 'n.'], ['quantity', 'n.'], ['quarrel', 'n.'], ['quarter', 'n.'], ['radar', 'n.'], ['radiant', 'adj.'], ['radiation', 'n.'],
  ['range', 'n.'], ['rank', 'n.'], ['rapid', 'adj.'], ['rare', 'adj.'], ['rate', 'n.'], ['raw', 'adj.'], ['reaction', 'n.'], ['readily', 'adv.'],
  ['reality', 'n.'], ['realize', 'v.'], ['receipt', 'n.'], ['reckon', 'v.'], ['recognition', 'n.'], ['recognize', 'v.'], ['recommend', 'v.'], ['recover', 'v.'],
  ['recovery', 'n.'], ['reduce', 'v.'], ['refer', 'v.'], ['reference', 'n.'], ['reflect', 'v.'], ['reform', 'v.'], ['refresh', 'v.'], ['refuse', 'v.'],
  ['regard', 'v.'], ['region', 'n.'], ['regular', 'adj.'], ['reject', 'v.'], ['relation', 'n.'], ['relationship', 'n.'], ['relative', 'n.'], ['relax', 'v.'],
  ['release', 'v.'], ['reliable', 'adj.'], ['relief', 'n.'], ['relieve', 'v.'], ['religion', 'n.'], ['religious', 'adj.'], ['rely', 'v.'], ['remain', 'v.'],
  ['remark', 'n.'], ['remarkable', 'adj.'], ['remedy', 'n.'], ['remind', 'v.'], ['remote', 'adj.'], ['remove', 'v.'], ['renew', 'v.'], ['repair', 'v.'],
  ['replace', 'v.'], ['reply', 'v.'], ['represent', 'v.'], ['representative', 'n.'], ['republic', 'n.'], ['reputation', 'n.'], ['request', 'n.'], ['require', 'v.'],
  ['requirement', 'n.'], ['rescue', 'v.'], ['research', 'n.'], ['reserve', 'v.'], ['resident', 'n.'], ['resist', 'v.'], ['resource', 'n.'], ['respect', 'n.'],
  ['respond', 'v.'], ['response', 'n.'], ['responsibility', 'n.'], ['responsible', 'adj.'], ['restore', 'v.'], ['restrict', 'v.'], ['retire', 'v.'], ['retreat', 'v.'],
  ['reveal', 'v.'], ['review', 'n.'], ['revise', 'v.'], ['revolution', 'n.'], ['reward', 'n.'], ['rhythm', 'n.'], ['ribbon', 'n.'], ['rid', 'adj.'],
  ['riddle', 'n.'], ['ridiculous', 'adj.'], ['ripe', 'adj.'], ['risk', 'n.'], ['rival', 'n.'], ['roar', 'v.'], ['roast', 'v.'], ['rob', 'v.'],
  ['robber', 'n.'], ['robbery', 'n.'], ['robe', 'n.'], ['rocket', 'n.'], ['romantic', 'adj.'], ['rot', 'v.'], ['rotten', 'adj.'], ['rough', 'adj.'],
  ['route', 'n.'], ['routine', 'n.'], ['rug', 'n.'], ['ruin', 'v.'], ['rumor', 'n.'], ['runner', 'n.'], ['rural', 'adj.'], ['rush', 'v.'],
  ['rust', 'n.'], ['rusty', 'adj.'], ['sack', 'n.'], ['sacred', 'adj.'], ['sacrifice', 'n.'], ['sail', 'v.'], ['sailor', 'n.'], ['salary', 'n.'],
  ['sauce', 'n.'], ['saucer', 'n.'], ['sausage', 'n.'], ['scale', 'n.'], ['scarce', 'adj.'], ['scenery', 'n.'], ['schedule', 'n.'], ['scheme', 'n.'],
  ['scholar', 'n.'], ['scholarship', 'n.'], ['scold', 'v.'], ['scout', 'n.'], ['scratch', 'v.'], ['scream', 'v.'], ['seal', 'n.'], ['secondary', 'adj.'],
  ['section', 'n.'], ['security', 'n.'], ['seek', 'v.'], ['seize', 'v.'], ['select', 'v.'], ['selection', 'n.'], ['semester', 'n.'], ['sense', 'n.'],
  ['sensible', 'adj.'], ['sensitive', 'adj.'], ['separation', 'n.'], ['servant', 'n.'], ['service', 'n.'], ['settle', 'v.'], ['settlement', 'n.'], ['severe', 'adj.'],
  ['sew', 'v.'], ['shade', 'n.'], ['shadow', 'n.'], ['shallow', 'adj.'], ['shame', 'n.'], ['shampoo', 'n.'], ['shave', 'v.'], ['shelf', 'n.'],
  ['shell', 'n.'], ['shelter', 'n.'], ['shift', 'v.'], ['shock', 'n.'], ['shoot', 'v.'], ['shore', 'n.'], ['shortage', 'n.'], ['shortly', 'adv.'],
  ['shrimp', 'n.'], ['shrink', 'v.'], ['sigh', 'v.'], ['signal', 'n.'], ['signature', 'n.'], ['significance', 'n.'], ['significant', 'adj.'], ['silence', 'n.'],
  ['silent', 'adj.'], ['silk', 'n.'], ['silly', 'adj.'], ['silver', 'n.'], ['similar', 'adj.'], ['similarity', 'n.'], ['sincere', 'adj.'], ['sink', 'v.'],
  ['site', 'n.'], ['situation', 'n.'], ['sketch', 'n.'], ['skill', 'n.'], ['skillful', 'adj.'], ['skin', 'n.'], ['skate', 'v.'], ['slave', 'n.'],
  ['sleeve', 'n.'], ['slight', 'adj.'], ['slope', 'n.'], ['smooth', 'adj.'], ['snap', 'v.'], ['sneeze', 'v.'], ['sob', 'v.'], ['social', 'adj.'],
  ['society', 'n.'], ['soft', 'adj.'], ['software', 'n.'], ['soil', 'n.'], ['solid', 'adj.'], ['solution', 'n.'], ['solve', 'v.'], ['somewhat', 'adv.'],
  ['sorrow', 'n.'], ['soul', 'n.'], ['spare', 'adj.'], ['spark', 'n.'], ['sparkle', 'v.'], ['spear', 'n.'], ['species', 'n.'], ['specific', 'adj.'],
  ['specimen', 'n.'], ['spectacle', 'n.'], ['spectator', 'n.'], ['speech', 'n.'], ['speed', 'n.'], ['spirit', 'n.'], ['spiritual', 'adj.'], ['spit', 'v.'],
  ['spite', 'n.'], ['splendid', 'adj.'], ['split', 'v.'], ['spoil', 'v.'], ['sponge', 'n.'], ['spray', 'v.'], ['spread', 'v.'], ['squeeze', 'v.'],
  ['stable', 'adj.'], ['stadium', 'n.'], ['staff', 'n.'], ['stage', 'n.'], ['stain', 'n.'], ['standard', 'n.'], ['stare', 'v.'], ['state', 'n.'],
  ['statement', 'n.'], ['statue', 'n.'], ['status', 'n.'], ['steam', 'n.'], ['steel', 'n.'], ['steep', 'adj.'], ['stem', 'n.'], ['stereo', 'n.'],
  ['sticky', 'adj.'], ['stiff', 'adj.'], ['stir', 'v.'], ['stitch', 'n.'], ['stock', 'n.'], ['stocking', 'n.'], ['stone', 'n.'], ['stool', 'n.'],
  ['storage', 'n.'], ['stove', 'n.'], ['strain', 'n.'], ['strap', 'n.'], ['strategy', 'n.'], ['stream', 'n.'], ['strength', 'n.'], ['strengthen', 'v.'],
  ['stress', 'n.'], ['stretch', 'v.'], ['strict', 'adj.'], ['strike', 'v.'], ['string', 'n.'], ['strip', 'n.'], ['stripe', 'n.'], ['stroke', 'n.'],
  ['structure', 'n.'], ['struggle', 'v.'], ['stubborn', 'adj.'], ['studio', 'n.'], ['stuff', 'n.'], ['style', 'n.'], ['substance', 'n.'], ['subway', 'n.'],
  ['succeed', 'v.'], ['success', 'n.'], ['suck', 'v.'], ['sudden', 'adj.'], ['suffer', 'v.'], ['sufficient', 'adj.'], ['suggest', 'v.'], ['suggestion', 'n.'],
  ['suit', 'n.'], ['suitable', 'adj.'], ['suitcase', 'n.'], ['summary', 'n.'], ['summit', 'n.'], ['sunlight', 'n.'], ['sunrise', 'n.'], ['sunset', 'n.'],
  ['sunshine', 'n.'], ['super', 'adj.'], ['superior', 'adj.'], ['supply', 'v.'], ['support', 'v.'], ['supporter', 'n.'], ['suppose', 'v.'], ['supreme', 'adj.'],
  ['surface', 'n.'], ['surgeon', 'n.'], ['surgery', 'n.'], ['surround', 'v.'], ['survive', 'v.'], ['suspect', 'v.'], ['suspend', 'v.'], ['swallow', 'v.'],
  ['swan', 'n.'], ['swear', 'v.'], ['sweat', 'n.'], ['swell', 'v.'], ['swift', 'adj.'], ['switch', 'n.'], ['sword', 'n.'], ['sympathy', 'n.'],
  ['system', 'n.'], ['tailor', 'n.'], ['tale', 'n.'], ['target', 'n.'], ['task', 'n.'], ['tax', 'n.'], ['teapot', 'n.'], ['teaspoon', 'n.'],
  ['technical', 'adj.'], ['technique', 'n.'], ['technology', 'n.'], ['temperature', 'n.'], ['temporary', 'adj.'], ['tend', 'v.'], ['tendency', 'n.'], ['tender', 'adj.'],
  ['tense', 'adj.'], ['tension', 'n.'], ['tent', 'n.'], ['term', 'n.'], ['terrific', 'adj.'], ['theme', 'n.'], ['theory', 'n.'], ['thief', 'n.'],
  ['thirst', 'n.'], ['thorn', 'n.'], ['threat', 'n.'], ['threaten', 'v.'], ['thrill', 'n.'], ['throughout', 'prep.'], ['thumb', 'n.'], ['thunder', 'n.'],
  ['thus', 'adv.'], ['tide', 'n.'], ['timber', 'n.'], ['timely', 'adj.'], ['tin', 'n.'], ['tiptoe', 'v.'], ['tissue', 'n.'], ['title', 'n.'],
  ['tobacco', 'n.'], ['tolerate', 'v.'], ['toll', 'n.'], ['tomb', 'n.'], ['tone', 'n.'], ['tongue', 'n.'], ['tool', 'n.'], ['topic', 'n.'],
  ['torch', 'n.'], ['tortoise', 'n.'], ['tour', 'n.'], ['tourism', 'n.'], ['tourist', 'n.'], ['trace', 'v.'], ['track', 'n.'], ['trade', 'n.'],
  ['trader', 'n.'], ['tradition', 'n.'], ['traditional', 'adj.'], ['tragedy', 'n.'], ['trail', 'n.'], ['training', 'n.'], ['transfer', 'v.'], ['transform', 'v.'],
  ['translate', 'v.'], ['translation', 'n.'], ['transport', 'n.'], ['transportation', 'n.'], ['trap', 'n.'], ['traveler', 'n.'], ['tray', 'n.'], ['treaty', 'n.'],
  ['tremble', 'v.'], ['trend', 'n.'], ['trial', 'n.'], ['triangle', 'n.'], ['tribe', 'n.'], ['troop', 'n.'], ['tropical', 'adj.'], ['trumpet', 'n.'],
  ['trust', 'v.'], ['truth', 'n.'], ['tube', 'n.'], ['tune', 'n.'], ['tunnel', 'n.'], ['tutor', 'n.'], ['twig', 'n.'], ['twin', 'n.'],
  ['twist', 'v.'], ['typewriter', 'n.'], ['typical', 'adj.'], ['unable', 'adj.'], ['unbelievable', 'adj.'], ['uncertain', 'adj.'], ['underground', 'adj.'], ['underline', 'v.'],
  ['underneath', 'prep.'], ['understandable', 'adj.'], ['underwear', 'n.'], ['undoubtedly', 'adv.'], ['unexpected', 'adj.'], ['unfortunate', 'adj.'], ['union', 'n.'], ['unique', 'adj.'],
  ['universe', 'n.'], ['universal', 'adj.'], ['university', 'n.'], ['unknown', 'adj.'], ['unless', 'conj.'], ['unlike', 'prep.'], ['unlikely', 'adj.'], ['unnecessary', 'adj.'],
  ['unpleasant', 'adj.'], ['unreasonable', 'adj.'], ['unusual', 'adj.'], ['upset', 'adj.'], ['upstairs', 'adv.'], ['upward', 'adv.'], ['urban', 'adj.'], ['urge', 'v.'],
  ['urgent', 'adj.'], ['usage', 'n.'], ['usual', 'adj.'], ['valley', 'n.'], ['valuable', 'adj.'], ['value', 'n.'], ['van', 'n.'], ['vanish', 'v.'],
  ['variety', 'n.'], ['various', 'adj.'], ['vase', 'n.'], ['vast', 'adj.'], ['vehicle', 'n.'], ['venture', 'n.'], ['verb', 'n.'], ['verse', 'n.'],
  ['version', 'n.'], ['vessel', 'n.'], ['victim', 'n.'], ['victory', 'n.'], ['view', 'n.'], ['village', 'n.'], ['villager', 'n.'], ['vinegar', 'n.'],
  ['violence', 'n.'], ['violent', 'adj.'], ['virtue', 'n.'], ['visible', 'adj.'], ['vision', 'n.'], ['visual', 'adj.'], ['vital', 'adj.'], ['vivid', 'adj.'],
  ['vocabulary', 'n.'], ['volcano', 'n.'], ['volleyball', 'n.'], ['volume', 'n.'], ['volunteer', 'n.'], ['vote', 'v.'], ['vowel', 'n.'], ['voyage', 'n.'],
  ['wage', 'n.'], ['wagon', 'n.'], ['waist', 'n.'], ['wander', 'v.'], ['ware', 'n.'], ['warehouse', 'n.'], ['warfare', 'n.'], ['warmth', 'n.'],
  ['warn', 'v.'], ['warning', 'n.'], ['warrior', 'n.'], ['wax', 'n.'], ['weapon', 'n.'], ['weave', 'v.'], ['web', 'n.'], ['wedding', 'n.'],
  ['weed', 'n.'], ['weekly', 'adj.'], ['weep', 'v.'], ['weigh', 'v.'], ['weight', 'n.'], ['wheat', 'n.'], ['whisper', 'v.'], ['whistle', 'v.'],
  ['wicked', 'adj.'], ['widow', 'n.'], ['widower', 'n.'], ['width', 'n.'], ['willing', 'adj.'], ['wind', 'v.'], ['wing', 'n.'], ['wipe', 'v.'],
  ['wire', 'n.'], ['wisdom', 'n.'], ['wit', 'n.'], ['withdraw', 'v.'], ['witness', 'n.'], ['wolf', 'n.'], ['wool', 'n.'], ['worm', 'n.'],
  ['worn', 'adj.'], ['worship', 'v.'], ['worth', 'prep.'], ['worthwhile', 'adj.'], ['worthy', 'adj.'], ['wound', 'n.'], ['wrap', 'v.'], ['wreck', 'n.'],
  ['wrist', 'n.'], ['x-ray', 'n.'], ['yacht', 'n.'], ['yawn', 'v.'], ['yell', 'v.'], ['yield', 'v.'], ['youngster', 'n.'], ['youth', 'n.']
]

async function generate() {
  const seen = new Set<string>()
  const allEntries: Array<{ word: string; pos: string }> = []

  for (const [word, pos] of core1200Words) {
    const slug = word.toLowerCase().replace(/[^a-z0-9]/g, '-')
    if (!seen.has(slug)) {
      seen.add(slug)
      allEntries.push({ word, pos })
    }
  }

  for (const [word, pos] of extension800Words) {
    const slug = word.toLowerCase().replace(/[^a-z0-9]/g, '-')
    if (!seen.has(slug)) {
      seen.add(slug)
      allEntries.push({ word, pos })
    }
  }

  // Exactly 1,200 Core Junior High words + 800 Extension words = 2,000 Canonical Words
  const vocabList: any[] = []
  const targetCoreCount = 1200
  const targetExtCount = 800
  const totalTarget = targetCoreCount + targetExtCount

  const selectedEntries = allEntries.slice(0, totalTarget)

  for (let i = 0; i < selectedEntries.length; i++) {
    const { word, pos } = selectedEntries[i]!
    const slug = word.toLowerCase().replace(/[^a-z0-9]/g, '-')
    vocabList.push({
      id: `v-${slug}`,
      word,
      partOfSpeech: pos,
      band: i < targetCoreCount ? 'core-1200' : 'ext-800',
    })
  }

  const outputPath = resolve(REPO_ROOT, 'packages/generator/src/curriculum-maps/official/vocabulary-2000.json')
  await writeFile(outputPath, JSON.stringify(vocabList, null, 2), 'utf8')
  console.log(`Generated ${vocabList.length} canonical vocabulary entries in ${outputPath} (Core: ${vocabList.filter(v => v.band === 'core-1200').length}, Ext: ${vocabList.filter(v => v.band === 'ext-800').length})`)
}

generate().catch(console.error)
