export interface GrammarProgressionUnit {
  unitId: string
  gradeStage: 'grade_7' | 'grade_8' | 'grade_9'
  officialAppendix6Id: string
  titleZh: string
  patterns: string[]
  prerequisites: string[]
  taiwaneseStudentTrapsZh: string
  annotationSource: 'paper-english-derived'
}

export const grammarProgressionUnits: GrammarProgressionUnit[] = [
  // Grade 7 (基礎句構、時態與日常問答)
  {
    unitId: 'g7-be-verbs-pronouns',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-be-verbs-pronouns',
    titleZh: 'be 動詞與人稱代名詞格位',
    patterns: ['Subject + am/is/are + Complement', 'Subject + be + not + Complement'],
    prerequisites: [],
    taiwaneseStudentTrapsZh: '易將主詞與所有格搞混（如誤寫 He book is new 或 They is students）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-present-simple-verbs',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-present-simple',
    titleZh: '現在簡單式第三人稱單數動詞變化',
    patterns: ['He/She/It + V-s/es', 'Subject + don’t/doesn’t + 原形動詞'],
    prerequisites: ['g7-be-verbs-pronouns'],
    taiwaneseStudentTrapsZh: '忘記第三人稱單數動詞加 s，或在 doesn’t 後面又加 s（如 He doesn’t plays）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-do-does-questions',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-present-simple',
    titleZh: '現在簡單式 Do / Does 疑問句與動詞還原',
    patterns: ['Do/Does + Subject + 原形動詞...?'],
    prerequisites: ['g7-present-simple-verbs'],
    taiwaneseStudentTrapsZh: 'Does 開頭的問句中，後方主要動詞忘記回到原形（如 Does he likes apples?）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-modals-ability-permission',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-modals-ability-permission',
    titleZh: '情態助動詞：能力與許可 (can / may)',
    patterns: ['Subject + can/cannot + 原形動詞', 'Can/May + Subject + 原形動詞...?'],
    prerequisites: ['g7-present-simple-verbs'],
    taiwaneseStudentTrapsZh: 'can / may 後面誤加 to 或動詞變化（如 can to swim、can swims）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-present-continuous',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-present-continuous',
    titleZh: '現在進行式 (be + V-ing)',
    patterns: ['Subject + is/am/are + V-ing', 'Is/Are + Subject + V-ing...?'],
    prerequisites: ['g7-be-verbs-pronouns'],
    taiwaneseStudentTrapsZh: '常漏掉 be 動詞直接寫 V-ing（如 He playing games）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-imperatives',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-imperatives',
    titleZh: '祈使句與指示命令 (Please / Don’t)',
    patterns: ['原形動詞 + Object, please.', 'Don’t + 原形動詞.'],
    prerequisites: [],
    taiwaneseStudentTrapsZh: '祈使句開頭誤用 V-ing 或名詞主詞。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-there-is-are',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-there-is-are',
    titleZh: 'There is / There are 存在句',
    patterns: ['There is + 單數名詞/不可數名詞', 'There are + 複數名詞'],
    prerequisites: ['g7-be-verbs-pronouns'],
    taiwaneseStudentTrapsZh: '中文「有」容易誤寫成 There have a book。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-time-place-prepositions',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-prepositions-time-place',
    titleZh: '時間與地方介系詞 (at/on/in/under)',
    patterns: ['at + 鐘點/特定地點', 'on + 星期/日期/平面', 'in + 月份/年份/空間內部'],
    prerequisites: [],
    taiwaneseStudentTrapsZh: 'at Monday, in 8:00 等介系詞混淆。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g7-wh-questions',
    gradeStage: 'grade_7',
    officialAppendix6Id: 'og-wh-questions',
    titleZh: 'Wh- 資訊疑問句',
    patterns: ['What/Where/When/Who/Why/How + aux/be + Subject + Verb...?'],
    prerequisites: ['g7-do-does-questions'],
    taiwaneseStudentTrapsZh: '疑問詞後面直接接主詞而漏掉助動詞（如 Where you go?）。',
    annotationSource: 'paper-english-derived',
  },

  // Grade 8 (過去時態、未來式、助動詞、副詞子句與比較)
  {
    unitId: 'g8-past-simple-verbs',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-past-simple',
    titleZh: '過去簡單式規則與不規則動詞變化',
    patterns: ['Subject + Ved / 不規則過去動詞', 'Subject + didn’t + 原形動詞'],
    prerequisites: ['g7-present-simple-verbs'],
    taiwaneseStudentTrapsZh: 'didn’t 後面忘記將動詞還原為原形（如 didn’t went）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-past-continuous',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-past-continuous',
    titleZh: '過去進行式與 when / while 子句連用',
    patterns: ['Subject + was/were + V-ing (when + 過去簡單式)'],
    prerequisites: ['g8-past-simple-verbs', 'g7-present-continuous'],
    taiwaneseStudentTrapsZh: 'was/were 選擇錯誤或與過去簡單式混用時態錯置。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-future-tense',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-future-tense',
    titleZh: '未來式 (will / be going to)',
    patterns: ['Subject + will + 原形動詞', 'Subject + be going to + 原形動詞'],
    prerequisites: ['g7-be-verbs-pronouns'],
    taiwaneseStudentTrapsZh: 'will 後面誤加 to 或動詞變化（如 will goes）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-modals-obligation-advice',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-modals-obligation-advice',
    titleZh: '情態助動詞 (must / should / have to)',
    patterns: ['Subject + must/should/can + 原形動詞', 'Subject + have/has to + 原形動詞'],
    prerequisites: ['g7-present-simple-verbs'],
    taiwaneseStudentTrapsZh: '情態助動詞後面誤加 s（如 He should goes）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-adverbial-clauses-time-reason',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-adverbial-clauses-time-reason',
    titleZh: '時間與原因副詞子句 (before/after/when/because/although)',
    patterns: ['Because / Although + S1 + V1, S2 + V2.', 'S1 + V1 before/after + S2 + V2.'],
    prerequisites: ['g8-past-simple-verbs'],
    taiwaneseStudentTrapsZh: '中文「因為...所以...」或「雖然...但是...」易同時出現 Because... so... 或 Although... but...。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-gerunds-infinitives',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-gerunds-infinitives',
    titleZh: '動名詞 (V-ing) 與不定詞 (to + V) 當主詞與受詞',
    patterns: ['V-ing + is + Adj.', 'Subject + enjoy/finish/practice + V-ing', 'Subject + want/hope/decide + to V'],
    prerequisites: ['g7-present-simple-verbs'],
    taiwaneseStudentTrapsZh: '接動名詞或不定詞的特定動詞慣用法混淆（如 enjoy to read）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-comparatives-superlatives',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-comparatives-superlatives',
    titleZh: '形容詞與副詞比較級與最高級 (-er / more / -est / most)',
    patterns: ['A is + -er / more Adj. + than B', 'A is the + -est / most Adj. in/of...'],
    prerequisites: ['g7-be-verbs-pronouns'],
    taiwaneseStudentTrapsZh: '重複使用 more + -er（如 more taller），或最高級漏掉 the。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g8-sense-causative-verbs',
    gradeStage: 'grade_8',
    officialAppendix6Id: 'og-sense-causative-verbs',
    titleZh: '感官動詞與使役動詞 (see/hear/make/have/let)',
    patterns: ['Subject + see/hear + Object + 原形動詞 / V-ing', 'Subject + make/let/have + Object + 原形動詞'],
    prerequisites: ['g8-past-simple-verbs'],
    taiwaneseStudentTrapsZh: '使役動詞後方受詞補語誤加 to（如 make him to cry）。',
    annotationSource: 'paper-english-derived',
  },

  // Grade 9 (現在完成式、被動語態、子句結構、關係代名詞與條件句)
  {
    unitId: 'g9-present-perfect-experience',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-present-perfect',
    titleZh: '現在完成式：經驗與完成 (have/has + p.p., already/yet/never)',
    patterns: ['Subject + have/has + p.p.', 'Have/Has + Subject + ever + p.p.?'],
    prerequisites: ['g8-past-simple-verbs'],
    taiwaneseStudentTrapsZh: '將動詞過去式 (Ved) 與過去分詞 (p.p.) 混淆，或主詞第三人稱單數漏用 has。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-present-perfect-duration',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-present-perfect',
    titleZh: '現在完成式：持續狀態與 since / for 的辨析',
    patterns: ['Subject + have/has + p.p. + for + 一段時間', 'Subject + have/has + p.p. + since + 起點時間/過去式子句'],
    prerequisites: ['g9-present-perfect-experience'],
    taiwaneseStudentTrapsZh: 'since 接一段時間或 for 接特定時間點（如 since three years 誤用）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-passive-voice',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-passive-voice',
    titleZh: '被動語態 (be + p.p.)',
    patterns: ['Subject + is/are/was/were + p.p. (+ by Object)'],
    prerequisites: ['g8-past-simple-verbs', 'g9-present-perfect-experience'],
    taiwaneseStudentTrapsZh: '被動語態中漏掉 be 動詞（如 The car washed yesterday）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-noun-clauses-that',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-noun-clauses',
    titleZh: 'That 引導之名詞子句',
    patterns: ['Subject + think/know/believe + (that) + S + V'],
    prerequisites: ['g8-adverbial-clauses-time-reason'],
    taiwaneseStudentTrapsZh: 'that 子句中誤將動詞提前形成疑問句倒裝。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-indirect-questions',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-indirect-questions',
    titleZh: '間接問句 (Wh-word + S + V / whether... or not)',
    patterns: ['Do you know + Wh-word + S + V?', 'Please tell me + whether/if + S + V.'],
    prerequisites: ['g7-wh-questions', 'g9-noun-clauses-that'],
    taiwaneseStudentTrapsZh: '間接問句誤用一般疑問句倒裝（如 Do you know where is he?）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-relative-clauses-subject',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-relative-clauses',
    titleZh: '關係子句：主格關係代名詞 (who / which / that)',
    patterns: ['先行詞(人) + who/that + V', '先行詞(物) + which/that + V'],
    prerequisites: ['g8-gerunds-infinitives'],
    taiwaneseStudentTrapsZh: '關係代名詞後方的動詞單複數未與先行詞一致（如 The boy who play tennis）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-relative-clauses-object',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-relative-clauses',
    titleZh: '關係子句：受格關係代名詞與省略',
    patterns: ['先行詞 + (whom/which/that) + S + V'],
    prerequisites: ['g9-relative-clauses-subject'],
    taiwaneseStudentTrapsZh: '關係子句中重複保留受詞代名詞（如 The book that I bought it yesterday）。',
    annotationSource: 'paper-english-derived',
  },
  {
    unitId: 'g9-conditionals',
    gradeStage: 'grade_9',
    officialAppendix6Id: 'og-conditionals',
    titleZh: '第一條件句 (If + 現在式, 主要子句 + will/can + V)',
    patterns: ['If + S + 現在簡單式, S + will + 原形動詞.'],
    prerequisites: ['g8-future-tense', 'g8-adverbial-clauses-time-reason'],
    taiwaneseStudentTrapsZh: 'If 條件子句中誤用未來式 will（如 If it will rain tomorrow）。',
    annotationSource: 'paper-english-derived',
  },
]

export function getGrammarUnit(unitId: string): GrammarProgressionUnit | undefined {
  return grammarProgressionUnits.find((u) => u.unitId === unitId)
}

export function getUnitsByGradeStage(gradeStage: 'grade_7' | 'grade_8' | 'grade_9'): GrammarProgressionUnit[] {
  return grammarProgressionUnits.filter((u) => u.gradeStage === gradeStage)
}
